# Data Wrangling for WeRateDogs twitter handle

WeRateDogs is a Twitter handle that rates dogs on a scale of 10 and posts it along with a picture or video submitted to the account by the owner. Rating often go above 10 and this has definitely made this rating system unique. The twitter handle has above 6.9 million followers and an online shopping store for dogs and dog owners that relies on marketing through this handle. 

In order to analyze the twitter feeds of for this account it is important to wrangle a dataset for it. In this notebook, you will be able to see the data wrangling efforts made before analyzing the twitter feeds of WeRateDogs.

**Data wrangling process**
The data wrangling process for this projectt will be divided into three major components:

1. Gather
    - Involves gathering different datasets needed to do the analysis. These datasets will be stored in different dataframes.
2. Assess
    - The gathered data will be assessed for cleaning and tidiness issues and all problems will be documented for further cleaning
3. Clean
    - Retify cleaning and tidiness issues that are documented in the assessment step

## Project

In [1]:
#imports
import numpy as np
import pandas as pd
import requests
import io
import tweepy
import json
import os
import time
import re
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set_style('darkgrid' )

## Gather

**Reading in the twitter archive**

In [2]:
df_1=pd.read_csv("twitter-archive-enhanced.csv")

**Retrieving the image prediction data from cloud**

In [3]:
# Used read_csv instead of the requests library since it seemed more efficient and could be done using less code
# the udacity mentor said it should be alright
url = "https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv"
df_2= pd.read_csv(url, sep = "\t")

# code to use requests for programatic download
import csv

url = "https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv"
download = requests.get(url)

with open('image_predictions.tsv', 'wb') as file:
    file.write(download.content)

# create dataframe
df_2= pd.read_csv('image_predictions.tsv', sep = "\t")

**Accessing Twitter API to get additional data**

Authorization for access

In [4]:
# the information is stored in txt file line by line
with open("tokens.txt") as token:
    consumer_key = token.readline().strip()
    consumer_secret = token.readline().strip()
    access_token = token.readline().strip()
    access_secret = token.readline().strip()

In [5]:
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

Saving twitter API data in a .txt file for use, to avoid repeatedly querying the API since it takes long
- can also be done using pickling

In [6]:
tweet_id_list=df_1['tweet_id'].tolist()

#appends json by line but also adds \n at the end 
start = time.time()
error_tweet_list=[]
success_tweets= []
with open('tweet_json.txt', 'a') as tweet_json:
    for count,tweet in enumerate(tweet_id_list):
        try:
            status_obj = api.get_status(tweet, tweet_mode='extended')
            json_str = json.dumps(status_obj._json)
            tweet_json.write(json_str + "\n")
            success_tweets.append(tweet)
            print (str(count)+". "+str(tweet)+": "+"Success") 
        except: 
            error_tweet_list.append(tweet)
            print (str(count)+". "+str(tweet)+": "+"FAIL! Tweet ID not found.")  
end = time.time()
print(str(end - start)+"seconds to complete")

0. 892420643555336193: Success
1. 892177421306343426: Success
2. 891815181378084864: Success
3. 891689557279858688: Success
4. 891327558926688256: Success
5. 891087950875897856: Success
6. 890971913173991426: Success
7. 890729181411237888: Success
8. 890609185150312448: Success
9. 890240255349198849: Success
10. 890006608113172480: Success
11. 889880896479866881: Success
12. 889665388333682689: Success
13. 889638837579907072: Success
14. 889531135344209921: Success
15. 889278841981685760: Success
16. 888917238123831296: Success
17. 888804989199671297: Success
18. 888554962724278272: Success
19. 888202515573088257: FAIL! Tweet ID not found.
20. 888078434458587136: Success
21. 887705289381826560: Success
22. 887517139158093824: Success
23. 887473957103951883: Success
24. 887343217045368832: Success
25. 887101392804085760: Success
26. 886983233522544640: Success
27. 886736880519319552: Success
28. 886680336477933568: Success
29. 886366144734445568: Success
30. 886267009285017600: Success
31. 886258384151887873: Success
32. 886054160059072513: Success
33. 885984800019947520: Success
34. 885528943205470208: Success
35. 885518971528720385: Success
36. 885311592912609280: Success
37. 885167619883638784: Success
38. 884925521741709313: Success
39. 884876753390489601: Success
40. 884562892145688576: Success
41. 884441805382717440: Success
42. 884247878851493888: Success
43. 884162670584377345: Success
44. 883838122936631299: Success
45. 883482846933004288: Success
46. 883360690899218434: Success
47. 883117836046086144: Success
48. 882992080364220416: Success
49. 882762694511734784: Success
50. 882627270321602560: Success
51. 882268110199369728: Success
52. 882045870035918850: Success
53. 881906580714921986: Success
54. 881666595344535552: Success
55. 881633300179243008: Success
56. 881536004380872706: Success
57. 881268444196462592: Success
58. 880935762899988482: Success
59. 880872448815771648: Success
60. 880465832366813184: Success
61. 880221127280381952: Success
62. 880095782870896641: Success
63. 879862464715927552: Success
64. 879674319642796034: Success
65. 879492040517615616: Success
66. 879415818425184262: Success
67. 879376492567855104: Success
68. 879130579576475649: Success
69. 879050749262655488: Success
70. 879008229531029506: Success
71. 878776093423087618: Success
72. 878604707211726852: Success
73. 878404777348136964: Success
74. 878316110768087041: Success
75. 878281511006478336: Success
76. 878057613040115712: Success
77. 877736472329191424: Success
78. 877611172832227328: Success
79. 877556246731214848: Success
80. 877316821321428993: Success
81. 877201837425926144: Success
82. 876838120628539392: Success
83. 876537666061221889: Success
84. 876484053909872640: Success
85. 876120275196170240: Success
86. 875747767867523072: Success
87. 875144289856114688: Success
88. 875097192612077568: Success
89. 875021211251597312: Success
90. 874680097055178752: Success
91. 874434818259525634: Success
92. 874296783580663808: Success
93. 874057562936811520: Success
94. 874012996292530176: Success
95. 873697596434513921: FAIL! Tweet ID not found.
96. 873580283840344065: Success
97. 873337748698140672: Success
98. 873213775632977920: Success
99. 872967104147763200: Success
100. 872820683541237760: Success
101. 872668790621863937: Success
102. 872620804844003328: Success
103. 872486979161796608: Success
104. 872261713294495745: Success
105. 872122724285648897: Success
106. 871879754684805121: Success
107. 871762521631449091: Success
108. 871515927908634625: Success
109. 871166179821445120: Success
110. 871102520638267392: Success
111. 871032628920680449: Success
112. 870804317367881728: Success
113. 870726314365509632: Success
114. 870656317836468226: Success
115. 870374049280663552: Success
116. 870308999962521604: Success
117. 870063196459192321: Success
118. 869988702071779329: FAIL! Tweet ID not found.
119. 869772420881756160: Success
120. 869702957897576449: Success
121. 869596645499047938: Success
122. 869227993411051520: Success
123. 868880397819494401: Success
124. 868639477480148993: Success
125. 868622495443632128: Success
126. 868552278524837888: Success
127. 867900495410671616: Success
128. 867774946302451713: Success
129. 867421006826221569: Success
130. 867072653475098625: Success
131. 867051520902168576: Success
132. 866816280283807744: FAIL! Tweet ID not found.
133. 866720684873056260: Success
134. 866686824827068416: Success
135. 866450705531457537: Success
136. 866334964761202691: Success
137. 866094527597207552: Success
138. 865718153858494464: Success
139. 865359393868664832: Success
140. 865006731092295680: Success
141. 864873206498414592: Success
142. 864279568663928832: Success
143. 864197398364647424: Success
144. 863907417377173506: Success
145. 863553081350529029: Success
146. 863471782782697472: Success
147. 863432100342583297: Success
148. 863427515083354112: Success
149. 863079547188785154: Success
150. 863062471531167744: Success
151. 862831371563274240: Success
152. 862722525377298433: Success
153. 862457590147678208: Success
154. 862096992088072192: Success
155. 861769973181624320: FAIL! Tweet ID not found.
156. 861383897657036800: Success
157. 861288531465048066: Success
158. 861005113778896900: Success
159. 860981674716409858: Success
160. 860924035999428608: Success
161. 860563773140209665: Success
162. 860524505164394496: Success
163. 860276583193509888: Success
164. 860184849394610176: Success
165. 860177593139703809: Success
166. 859924526012018688: Success
167. 859851578198683649: Success
168. 859607811541651456: Success
169. 859196978902773760: Success
170. 859074603037188101: Success
171. 858860390427611136: Success
172. 858843525470990336: Success
173. 858471635011153920: Success
174. 858107933456039936: Success
175. 857989990357356544: Success
176. 857746408056729600: Success
177. 857393404942143489: Success
178. 857263160327368704: Success
179. 857214891891077121: Success
180. 857062103051644929: Success
181. 857029823797047296: Success
182. 856602993587888130: Success
183. 856543823941562368: Success
184. 856526610513747968: Success
185. 856330835276025856: Success
186. 856288084350160898: Success
187. 856282028240666624: Success
188. 855862651834028034: Success
189. 855860136149123072: Success
190. 855857698524602368: Success
191. 855851453814013952: Success
192. 855818117272018944: Success
193. 855459453768019968: Success
194. 855245323840757760: Success
195. 855138241867124737: Success
196. 854732716440526848: Success
197. 854482394044301312: Success
198. 854365224396361728: Success
199. 854120357044912130: Success
200. 854010172552949760: Success
201. 853760880890318849: Success
202. 853639147608842240: Success
203. 853299958564483072: Success
204. 852936405516943360: Success
205. 852912242202992640: Success
206. 852672615818899456: Success
207. 852553447878664193: Success
208. 852311364735569921: Success
209. 852226086759018497: Success
210. 852189679701164033: Success
211. 851953902622658560: Success
212. 851861385021730816: Success
213. 851591660324737024: Success
214. 851464819735769094: Success
215. 851224888060895234: Success
216. 850753642995093505: Success
217. 850380195714523136: Success
218. 850333567704068097: Success
219. 850145622816686080: Success
220. 850019790995546112: Success
221. 849776966551130114: Success
222. 849668094696017920: Success
223. 849412302885593088: Success
224. 849336543269576704: Success
225. 849051919805034497: Success
226. 848690551926992896: Success
227. 848324959059550208: Success
228. 848213670039564288: Success
229. 848212111729840128: Success
230. 847978865427394560: Success
231. 847971574464610304: Success
232. 847962785489326080: Success
233. 847842811428974592: Success
234. 847617282490613760: Success
235. 847606175596138505: Success
236. 847251039262605312: Success
237. 847157206088847362: Success
238. 847116187444137987: Success
239. 846874817362120707: Success
240. 846514051647705089: Success
241. 846505985330044928: Success
242. 846153765933735936: Success
243. 846139713627017216: Success
244. 846042936437604353: Success
245. 845812042753855489: Success
246. 845677943972139009: Success
247. 845459076796616705: FAIL! Tweet ID not found.
248. 845397057150107648: Success

249. 845306882940190720: Success
250. 845098359547420673: Success
251. 844979544864018432: Success
252. 844973813909606400: Success
253. 844704788403113984: Success
254. 844580511645339650: Success
255. 844223788422217728: Success
256. 843981021012017153: Success
257. 843856843873095681: Success
258. 843604394117681152: Success
259. 843235543001513987: Success
260. 842892208864923648: FAIL! Tweet ID not found.
261. 842846295480000512: Success
262. 842765311967449089: Success
263. 842535590457499648: Success
264. 842163532590374912: Success
265. 842115215311396866: Success
266. 841833993020538882: Success
267. 841680585030541313: Success
268. 841439858740625411: Success
269. 841320156043304961: Success
270. 841314665196081154: Success
271. 841077006473256960: Success
272. 840761248237133825: Success
273. 840728873075638272: Success
274. 840698636975636481: Success
275. 840696689258311684: Success
276. 840632337062862849: Success
277. 840370681858686976: Success
278. 840268004936019968: Success
279. 839990271299457024: Success
280. 839549326359670784: Success
281. 839290600511926273: Success
282. 839239871831150596: Success
283. 838952994649550848: Success
284. 838921590096166913: Success
285. 838916489579200512: Success
286. 838831947270979586: Success
287. 838561493054533637: Success
288. 838476387338051585: Success
289. 838201503651401729: Success
290. 838150277551247360: Success
291. 838085839343206401: Success
292. 838083903487373313: Success
293. 837820167694528512: Success
294. 837482249356513284: Success
295. 837471256429613056: Success
296. 837366284874571778: Success
297. 837110210464448512: Success
298. 837012587749474308: FAIL! Tweet ID not found.
299. 836989968035819520: Success
300. 836753516572119041: Success
301. 836677758902222849: Success
302. 836648853927522308: Success
303. 836397794269200385: Success
304. 836380477523124226: Success
305. 836260088725786625: Success
306. 836001077879255040: Success
307. 835685285446955009: Success
308. 835574547218894849: Success
309. 835536468978302976: Success
310. 835309094223372289: Success
311. 835297930240217089: Success
312. 835264098648616962: Success
313. 835246439529840640: Success
314. 835172783151792128: Success
315. 835152434251116546: Success
316. 834931633769889797: Success
317. 834786237630337024: Success
318. 834574053763584002: Success
319. 834477809192075265: Success
320. 834458053273591808: Success
321. 834209720923721728: Success
322. 834167344700198914: Success
323. 834089966724603904: Success
324. 834086379323871233: Success
325. 833863086058651648: Success
326. 833826103416520705: Success
327. 833732339549220864: Success
328. 833722901757046785: Success
329. 833479644947025920: Success
330. 833124694597443584: Success
331. 832998151111966721: Success
332. 832769181346996225: Success
333. 832757312314028032: Success
334. 832682457690300417: Success
335. 832645525019123713: Success
336. 832636094638288896: Success
337. 832397543355072512: Success
338. 832369877331693569: Success
339. 832273440279240704: Success
340. 832215909146226688: Success
341. 832215726631055365: Success
342. 832088576586297345: Success
343. 832040443403784192: Success
344. 832032802820481025: Success
345. 831939777352105988: Success
346. 831926988323639298: Success
347. 831911600680497154: Success
348. 831670449226514432: Success
349. 831650051525054464: Success
350. 831552930092285952: Success
351. 831322785565769729: Success
352. 831315979191906304: Success
353. 831309418084069378: Success
354. 831262627380748289: Success
355. 830956169170665475: Success
356. 830583320585068544: Success
357. 830173239259324417: Success
358. 830097400375152640: Success
359. 829878982036299777: Success
360. 829861396166877184: Success
361. 829501995190984704: Success
362. 829449946868879360: Success
363. 829374341691346946: Success
364. 829141528400556032: Success
365. 829011960981237760: Success
366. 828801551087042563: Success
367. 828770345708580865: Success
368. 828708714936930305: Success
369. 828650029636317184: Success
370. 828409743546925057: Success
371. 828408677031882754: Success
372. 828381636999917570: Success
373. 828376505180889089: Success
374. 828372645993398273: Success
375. 828361771580813312: Success
376. 828046555563323392: Success
377. 828011680017821696: Success
378. 827933404142436356: Success
379. 827653905312006145: Success
380. 827600520311402496: Success
381. 827324948884643840: Success
382. 827228250799742977: FAIL! Tweet ID not found.
383. 827199976799354881: Success
384. 826958653328592898: Success
385. 826848821049180160: Success
386. 826615380357632002: Success
387. 826598799820865537: Success
388. 826598365270007810: Success
389. 826476773533745153: Success
390. 826240494070030336: Success
391. 826204788643753985: Success
392. 826115272272650244: Success
393. 825876512159186944: Success
394. 825829644528148480: Success
395. 825535076884762624: Success
396. 825147591692263424: Success
397. 825120256414846976: Success
398. 825026590719483904: Success
399. 824796380199809024: Success
400. 824775126675836928: Success
401. 824663926340194305: Success
402. 824325613288833024: Success
403. 824297048279236611: Success
404. 824025158776213504: Success
405. 823939628516474880: Success
406. 823719002937630720: Success
407. 823699002998870016: Success
408. 823581115634085888: Success
409. 823333489516937216: Success
410. 823322678127919110: Success
411. 823269594223824897: Success
412. 822975315408461824: Success
413. 822872901745569793: Success
414. 822859134160621569: Success
415. 822647212903690241: Success
416. 822610361945911296: Success
417. 822489057087389700: Success
418. 822462944365645825: Success
419. 822244816520155136: Success
420. 822163064745328640: Success
421. 821886076407029760: Success
422. 821813639212650496: Success
423. 821765923262631936: Success
424. 821522889702862852: Success
425. 821421320206483457: Success
426. 821407182352777218: Success
427. 821153421864615936: Success
428. 821149554670182400: Success
429. 821107785811234820: Success
430. 821044531881721856: Success
431. 820837357901512704: Success
432. 820749716845686786: Success
433. 820690176645140481: Success
434. 820494788566847489: Success
435. 820446719150292993: Success
436. 820314633777061888: Success
437. 820078625395449857: Success
438. 820013781606658049: Success
439. 819952236453363712: Success
440. 819924195358416896: Success
441. 819711362133872643: Success
442. 819588359383371776: Success
443. 819347104292290561: Success
444. 819238181065359361: Success
445. 819227688460238848: Success
446. 819015337530290176: Success
447. 819015331746349057: Success
448. 819006400881917954: Success
449. 819004803107983360: Success
450. 818646164899774465: Success
451. 818627210458333184: Success
452. 818614493328580609: Success
453. 818588835076603904: Success
454. 818536468981415936: Success
455. 818307523543449600: Success
456. 818259473185828864: Success
457. 818145370475810820: Success
458. 817908911860748288: Success
459. 817827839487737858: Success
460. 817777686764523521: Success
461. 817536400337801217: Success
462. 817502432452313088: Success
463. 817423860136083457: Success
464. 817415592588222464: Success
465. 817181837579653120: Success
466. 817171292965273600: Success
467. 817120970343411712: Success
468. 817056546584727552: Success
469. 816829038950027264: Success
470. 816816676327063552: Success
471. 816697700272001025: Success
472. 816450570814898180: Success
473. 816336735214911488: Success
474. 816091915477250048: Success
475. 816062466425819140: Success
476. 816014286006976512: Success
477. 815990720817401858: Success
478. 815966073409433600: Success
479. 815745968457060357: Success
480. 815736392542261248: Success
481. 815639385530101762: Success
482. 815390420867969024: Success
483. 814986499976527872: Success
484. 814638523311648768: Success
485. 814578408554463233: Success
486. 814530161257443328: Success
487. 814153002265309185: Success
488. 813944609378369540: Success
489. 813910438903693312: Success
490. 813812741911748608: Success
491. 813800681631023104: Success
492. 813217897535406080: Success
493. 813202720496779264: Success
494. 813187593374461952: Success
495. 813172488309972993: Success

496. 813157409116065792: Success
497. 813142292504645637: Success
498. 813130366689148928: Success
499. 813127251579564032: Success
500. 813112105746448384: Success
501. 813096984823349248: Success
502. 813081950185472002: Success
503. 813066809284972545: Success
504. 813051746834595840: Success
505. 812781120811126785: Success
506. 812747805718642688: Success
507. 812709060537683968: Success
508. 812503143955202048: Success
509. 812466873996607488: Success
510. 812372279581671427: Success
511. 811985624773361665: Success
512. 811744202451197953: Success
513. 811647686436880384: Success
514. 811627233043480576: Success
515. 811386762094317568: Success
516. 810984652412424192: Success
517. 810896069567610880: Success
518. 810657578271330305: Success
519. 810284430598270976: Success
520. 810254108431155201: Success
521. 809920764300447744: Success
522. 809808892968534016: Success
523. 809448704142938112: Success
524. 809220051211603969: Success
525. 809084759137812480: Success
526. 808838249661788160: Success
527. 808733504066486276: Success
528. 808501579447930884: Success
529. 808344865868283904: Success
530. 808134635716833280: Success
531. 808106460588765185: Success
532. 808001312164028416: Success
533. 807621403335917568: Success
534. 807106840509214720: Success
535. 807059379405148160: Success
536. 807010152071229440: Success
537. 806629075125202948: Success
538. 806620845233815552: Success
539. 806576416489959424: Success
540. 806542213899489280: Success
541. 806242860592926720: Success
542. 806219024703037440: Success
543. 805958939288408065: Success
544. 805932879469572096: Success
545. 805826884734976000: Success
546. 805823200554876929: Success
547. 805520635690676224: Success
548. 805487436403003392: Success
549. 805207613751304193: Success
550. 804738756058218496: Success
551. 804475857670639616: Success
552. 804413760345620481: Success
553. 804026241225523202: Success
554. 803773340896923648: Success
555. 803692223237865472: Success
556. 803638050916102144: Success
557. 803380650405482500: Success
558. 803321560782307329: Success
559. 803276597545603072: Success
560. 802952499103731712: Success
561. 802624713319034886: Success
562. 802600418706604034: Success
563. 802572683846291456: Success
564. 802323869084381190: Success
565. 802265048156610565: Success
566. 802247111496568832: FAIL! Tweet ID not found.
567. 802239329049477120: Success
568. 802185808107208704: Success
569. 801958328846974976: Success
570. 801854953262350336: Success
571. 801538201127157760: Success
572. 801285448605831168: Success
573. 801167903437357056: Success
574. 801127390143516673: Success
575. 801115127852503040: Success
576. 800859414831898624: Success
577. 800855607700029440: Success
578. 800751577355128832: Success
579. 800513324630806528: Success
580. 800459316964663297: Success
581. 800443802682937345: Success
582. 800388270626521089: Success
583. 800188575492947969: Success
584. 800141422401830912: Success
585. 800018252395122689: Success
586. 799774291445383169: Success
587. 799757965289017345: Success
588. 799422933579902976: Success
589. 799308762079035393: Success
590. 799297110730567681: Success
591. 799063482566066176: Success
592. 798933969379225600: Success
593. 798925684722855936: Success
594. 798705661114773508: Success
595. 798701998996647937: Success
596. 798697898615730177: Success
597. 798694562394996736: Success
598. 798686750113755136: Success
599. 798682547630837760: Success
600. 798673117451325440: Success
601. 798665375516884993: Success
602. 798644042770751489: Success
603. 798628517273620480: Success
604. 798585098161549313: Success
605. 798576900688019456: Success
606. 798340744599797760: Success
607. 798209839306514432: Success
608. 797971864723324932: Success
609. 797545162159308800: Success
610. 797236660651966464: Success
611. 797165961484890113: Success
612. 796904159865868288: Success
613. 796865951799083009: Success
614. 796759840936919040: Success
615. 796563435802726400: Success
616. 796484825502875648: Success
617. 796387464403357696: Success
618. 796177847564038144: Success
619. 796149749086875649: Success
620. 796125600683540480: Success
621. 796116448414461957: Success
622. 796080075804475393: Success
623. 796031486298386433: Success
624. 795464331001561088: Success
625. 795400264262053889: Success
626. 795076730285391872: Success
627. 794983741416415232: Success
628. 794926597468000259: Success
629. 794355576146903043: Success
630. 794332329137291264: Success
631. 794205286408003585: Success
632. 793962221541933056: Success
633. 793845145112371200: Success
634. 793614319594401792: Success
635. 793601777308463104: Success
636. 793500921481273345: Success
637. 793286476301799424: Success
638. 793271401113350145: Success
639. 793256262322548741: Success
640. 793241302385262592: Success
641. 793226087023144960: Success
642. 793210959003287553: Success
643. 793195938047070209: Success
644. 793180763617361921: Success
645. 793165685325201412: Success
646. 793150605191548928: Success
647. 793135492858580992: Success
648. 793120401413079041: Success
649. 792913359805018113: Success
650. 792883833364439040: Success
651. 792773781206999040: Success
652. 792394556390137856: Success
653. 792050063153438720: Success
654. 791821351946420224: Success
655. 791784077045166082: Success
656. 791780927877898241: Success
657. 791774931465953280: Success
658. 791672322847637504: Success
659. 791406955684368384: Success
660. 791312159183634433: Success
661. 791026214425268224: Success
662. 790987426131050500: Success
663. 790946055508652032: Success
664. 790723298204217344: Success
665. 790698755171364864: Success
666. 790581949425475584: Success
667. 790337589677002753: Success
668. 790277117346975746: Success
669. 790227638568808452: Success
670. 789986466051088384: Success
671. 789960241177853952: Success
672. 789903600034189313: Success
673. 789628658055020548: Success
674. 789599242079838210: Success
675. 789530877013393408: Success
676. 789314372632018944: Success
677. 789280767834746880: Success
678. 789268448748703744: Success
679. 789137962068021249: Success
680. 788908386943430656: Success
681. 788765914992902144: Success
682. 788552643979468800: Success
683. 788412144018661376: Success
684. 788178268662984705: Success
685. 788150585577050112: Success
686. 788070120937619456: Success
687. 788039637453406209: Success
688. 787810552592695296: Success
689. 787717603741622272: Success
690. 787397959788929025: Success
691. 787322443945877504: Success
692. 787111942498508800: Success
693. 786963064373534720: Success
694. 786729988674449408: Success
695. 786709082849828864: Success
696. 786664955043049472: Success
697. 786595970293370880: Success
698. 786363235746385920: Success
699. 786286427768250368: Success
700. 786233965241827333: Success
701. 786051337297522688: Success
702. 786036967502913536: Success
703. 785927819176054784: Success
704. 785872687017132033: Success
705. 785639753186217984: Success
706. 785533386513321988: Success
707. 785515384317313025: Success
708. 785264754247995392: Success
709. 785170936622350336: Success
710. 784826020293709826: Success
711. 784517518371221505: Success
712. 784431430411685888: Success
713. 784183165795655680: Success
714. 784057939640352768: Success
715. 783839966405230592: Success
716. 783821107061198850: Success
717. 783695101801398276: Success
718. 783466772167098368: Success
719. 783391753726550016: Success
720. 783347506784731136: Success
721. 783334639985389568: Success
722. 783085703974514689: Success
723. 782969140009107456: Success
724. 782747134529531904: Success
725. 782722598790725632: Success
726. 782598640137187329: Success
727. 782305867769217024: Success
728. 782021823840026624: Success
729. 781955203444699136: Success
730. 781661882474196992: Success
731. 781655249211752448: Success
732. 781524693396357120: Success
733. 781308096455073793: Success
734. 781251288990355457: Success
735. 781163403222056960: Success
736. 780931614150983680: Success
737. 780858289093574656: Success
738. 780800785462489090: Success
739. 780601303617732608: Success
740. 780543529827336192: Success
741. 780496263422808064: Success
742. 780476555013349377: Success
743. 780459368902959104: Success

744. 780192070812196864: Success
745. 780092040432480260: Success
746. 780074436359819264: Success
747. 779834332596887552: Success
748. 779377524342161408: Success
749. 779124354206535695: Success
750. 779123168116150273: Success
751. 779056095788752897: Success
752. 778990705243029504: Success
753. 778774459159379968: Success
754. 778764940568104960: Success
755. 778748913645780993: Success
756. 778650543019483137: Success
757. 778624900596654080: Success
758. 778408200802557953: Success
759. 778396591732486144: Success
760. 778383385161035776: Success
761. 778286810187399168: Success
762. 778039087836069888: Success
763. 778027034220126208: Success
764. 777953400541634568: Success
765. 777885040357281792: Success
766. 777684233540206592: Success
767. 777641927919427584: Success
768. 777621514455814149: Success
769. 777189768882946048: Success
770. 776819012571455488: Success
771. 776813020089548800: Success
772. 776477788987613185: Success
773. 776249906839351296: Success
774. 776218204058357768: Success
775. 776201521193218049: Success
776. 776113305656188928: Success
777. 776088319444877312: Success
778. 775898661951791106: Success
779. 775842724423557120: Success
780. 775733305207554048: Success
781. 775729183532220416: Success
782. 775364825476165632: Success
783. 775350846108426240: Success
784. 775096608509886464: FAIL! Tweet ID not found.
785. 775085132600442880: Success
786. 774757898236878852: Success
787. 774639387460112384: Success
788. 774314403806253056: Success
789. 773985732834758656: Success
790. 773922284943896577: Success
791. 773704687002451968: Success
792. 773670353721753600: Success
793. 773547596996571136: Success
794. 773336787167145985: Success
795. 773308824254029826: Success
796. 773247561583001600: Success
797. 773191612633579521: Success
798. 772877495989305348: Success
799. 772826264096874500: Success
800. 772615324260794368: Success
801. 772581559778025472: Success
802. 772193107915964416: Success
803. 772152991789019136: Success
804. 772117678702071809: Success
805. 772114945936949249: Success
806. 772102971039580160: Success
807. 771908950375665664: Success
808. 771770456517009408: Success
809. 771500966810099713: Success
810. 771380798096281600: Success
811. 771171053431250945: Success
812. 771136648247640064: Success
813. 771102124360998913: Success
814. 771014301343748096: Success
815. 771004394259247104: Success
816. 770787852854652928: Success
817. 770772759874076672: Success
818. 770743923962707968: Success
819. 770655142660169732: Success
820. 770414278348247044: Success
821. 770293558247038976: Success
822. 770093767776997377: Success
823. 770069151037685760: Success
824. 769940425801170949: Success
825. 769695466921623552: Success
826. 769335591808995329: Success
827. 769212283578875904: Success
828. 768970937022709760: Success
829. 768909767477751808: Success
830. 768855141948723200: Success
831. 768609597686943744: Success
832. 768596291618299904: Success
833. 768554158521745409: Success
834. 768473857036525572: Success
835. 768193404517830656: Success
836. 767884188863397888: Success
837. 767754930266464257: Success
838. 767500508068192258: Success
839. 767191397493538821: Success
840. 767122157629476866: Success
841. 766864461642756096: Success
842. 766793450729734144: Success
843. 766714921925144576: Success
844. 766693177336135680: Success
845. 766423258543644672: Success
846. 766313316352462849: Success
847. 766078092750233600: Success
848. 766069199026450432: Success
849. 766008592277377025: Success
850. 765719909049503744: Success
851. 765669560888528897: Success
852. 765395769549590528: Success
853. 765371061932261376: Success
854. 765222098633691136: Success
855. 764857477905154048: Success
856. 764259802650378240: Success
857. 763956972077010945: Success
858. 763837565564780549: Success
859. 763183847194451968: Success
860. 763167063695355904: Success
861. 763103485927849985: Success
862. 762699858130116608: Success
863. 762471784394268675: Success
864. 762464539388485633: Success
865. 762316489655476224: Success
866. 762035686371364864: Success
867. 761976711479193600: Success
868. 761750502866649088: Success
869. 761745352076779520: Success
870. 761672994376806400: Success
871. 761599872357261312: Success
872. 761371037149827077: Success
873. 761334018830917632: Success
874. 761292947749015552: Success
875. 761227390836215808: Success
876. 761004547850530816: Success
877. 760893934457552897: Success
878. 760656994973933572: Success
879. 760641137271070720: Success
880. 760539183865880579: Success
881. 760521673607086080: Success
882. 760290219849637889: Success
883. 760252756032651264: Success
884. 760190180481531904: Success
885. 760153949710192640: Success
886. 759943073749200896: Success
887. 759923798737051648: Success
888. 759846353224826880: Success
889. 759793422261743616: Success
890. 759566828574212096: Success
891. 759557299618865152: Success
892. 759447681597108224: Success
893. 759446261539934208: Success
894. 759197388317847553: Success
895. 759159934323924993: Success
896. 759099523532779520: Success
897. 759047813560868866: Success
898. 758854675097526272: Success
899. 758828659922702336: Success
900. 758740312047005698: Success
901. 758474966123810816: Success
902. 758467244762497024: Success
903. 758405701903519748: Success
904. 758355060040593408: Success
905. 758099635764359168: Success
906. 758041019896193024: Success
907. 757741869644341248: Success
908. 757729163776290825: Success
909. 757725642876129280: Success
910. 757611664640446465: Success
911. 757597904299253760: Success
912. 757596066325864448: Success
913. 757400162377592832: Success
914. 757393109802180609: Success
915. 757354760399941633: Success
916. 756998049151549440: Success
917. 756939218950160384: Success
918. 756651752796094464: Success
919. 756526248105566208: Success
920. 756303284449767430: Success
921. 756288534030475264: Success
922. 756275833623502848: Success
923. 755955933503782912: Success
924. 755206590534418437: Success
925. 755110668769038337: Success
926. 754874841593970688: Success
927. 754856583969079297: Success
928. 754747087846248448: Success
929. 754482103782404096: Success
930. 754449512966619136: Success
931. 754120377874386944: Success
932. 754011816964026368: Success
933. 753655901052166144: Success
934. 753420520834629632: Success
935. 753398408988139520: Success
936. 753375668877008896: Success
937. 753298634498793472: Success
938. 753294487569522689: Success
939. 753039830821511168: Success
940. 753026973505581056: Success
941. 752932432744185856: Success
942. 752917284578922496: Success
943. 752701944171524096: Success
944. 752682090207055872: Success
945. 752660715232722944: Success
946. 752568224206688256: Success
947. 752519690950500352: Success
948. 752334515931054080: Success
949. 752309394570878976: Success
950. 752173152931807232: Success
951. 751950017322246144: Success
952. 751937170840121344: Success
953. 751830394383790080: Success
954. 751793661361422336: Success
955. 751598357617971201: Success
956. 751583847268179968: Success
957. 751538714308972544: Success
958. 751456908746354688: Success
959. 751251247299190784: Success
960. 751205363882532864: Success
961. 751132876104687617: Success
962. 750868782890057730: Success
963. 750719632563142656: Success
964. 750506206503038976: Success
965. 750429297815552001: Success
966. 750383411068534784: Success
967. 750381685133418496: Success
968. 750147208377409536: Success
969. 750132105863102464: Success
970. 750117059602808832: Success
971. 750101899009982464: Success
972. 750086836815486976: Success
973. 750071704093859840: Success
974. 750056684286914561: Success
975. 750041628174217216: Success
976. 750026558547456000: Success
977. 750011400160841729: Success
978. 749996283729883136: Success
979. 749981277374128128: Success
980. 749774190421639168: Success
981. 749417653287129088: Success
982. 749403093750648834: Success
983. 749395845976588288: Success
984. 749317047558017024: Success
985. 749075273010798592: Success
986. 749064354620928000: Success
987. 749036806121881602: Success
988. 748977405889503236: Success
989. 748932637671223296: Success
990. 748705597323898880: Success
991. 748699167502000129: Success

992. 748692773788876800: Success
993. 748575535303884801: Success
994. 748568946752774144: Success
995. 748346686624440324: Success
996. 748337862848962560: Success
997. 748324050481647620: Success
998. 748307329658011649: Success
999. 748220828303695873: Success
1000. 747963614829678593: Success
1001. 747933425676525569: Success
1002. 747885874273214464: Success
1003. 747844099428986880: Success
1004. 747816857231626240: Success
1005. 747651430853525504: Success
1006. 747648653817413632: Success
1007. 747600769478692864: Success
1008. 747594051852075008: Success
1009. 747512671126323200: Success
1010. 747461612269887489: Success
1011. 747439450712596480: Success
1012. 747242308580548608: Success
1013. 747219827526344708: Success
1014. 747204161125646336: Success
1015. 747103485104099331: Success
1016. 746906459439529985: Success
1017. 746872823977771008: Success
1018. 746818907684614144: Success
1019. 746790600704425984: Success
1020. 746757706116112384: Success
1021. 746726898085036033: Success
1022. 746542875601690625: Success
1023. 746521445350707200: Success
1024. 746507379341139972: Success
1025. 746369468511756288: Success
1026. 746131877086527488: Success
1027. 746056683365994496: Success
1028. 745789745784041472: Success
1029. 745712589599014916: Success
1030. 745433870967832576: Success
1031. 745422732645535745: Success
1032. 745314880350101504: Success
1033. 745074613265149952: Success
1034. 745057283344719872: Success
1035. 744995568523612160: Success
1036. 744971049620602880: Success
1037. 744709971296780288: Success
1038. 744334592493166593: Success
1039. 744234799360020481: Success
1040. 744223424764059648: Success
1041. 743980027717509120: Success
1042. 743895849529389061: Success
1043. 743835915802583040: Success
1044. 743609206067040256: Success
1045. 743595368194129920: Success
1046. 743545585370791937: Success
1047. 743510151680958465: Success
1048. 743253157753532416: Success
1049. 743222593470234624: Success
1050. 743210557239623680: Success
1051. 742534281772302336: Success
1052. 742528092657332225: Success
1053. 742465774154047488: Success
1054. 742423170473463808: Success
1055. 742385895052087300: Success
1056. 742161199639494656: Success
1057. 742150209887731712: Success
1058. 741793263812808706: Success
1059. 741743634094141440: Success
1060. 741438259667034112: Success
1061. 741303864243200000: Success
1062. 741099773336379392: Success
1063. 741067306818797568: Success
1064. 740995100998766593: Success
1065. 740711788199743490: Success
1066. 740699697422163968: Success
1067. 740676976021798912: Success
1068. 740373189193256964: Success
1069. 740365076218183684: Success
1070. 740359016048689152: Success
1071. 740214038584557568: Success
1072. 739979191639244800: Success
1073. 739932936087216128: Success
1074. 739844404073074688: Success
1075. 739623569819336705: Success
1076. 739606147276148736: Success
1077. 739544079319588864: Success
1078. 739485634323156992: Success
1079. 739238157791694849: Success
1080. 738891149612572673: Success
1081. 738885046782832640: Success
1082. 738883359779196928: Success
1083. 738537504001953792: Success
1084. 738402415918125056: Success
1085. 738184450748633089: Success
1086. 738166403467907072: Success
1087. 738156290900254721: Success
1088. 737826014890496000: Success
1089. 737800304142471168: Success
1090. 737678689543020544: Success
1091. 737445876994609152: Success
1092. 737322739594330112: Success
1093. 737310737551491075: Success
1094. 736736130620620800: Success
1095. 736392552031657984: Success
1096. 736365877722001409: Success
1097. 736225175608430592: Success
1098. 736010884653420544: Success
1099. 735991953473572864: Success
1100. 735648611367784448: Success
1101. 735635087207878657: Success
1102. 735274964362878976: Success
1103. 735256018284875776: Success
1104. 735137028879360001: Success
1105. 734912297295085568: Success
1106. 734787690684657664: Success
1107. 734776360183431168: Success
1108. 734559631394082816: Success
1109. 733828123016450049: Success
1110. 733822306246479872: Success
1111. 733482008106668032: Success
1112. 733460102733135873: Success
1113. 733109485275860992: Success
1114. 732732193018155009: Success
1115. 732726085725589504: Success
1116. 732585889486888962: Success
1117. 732375214819057664: Success
1118. 732005617171337216: Success
1119. 731285275100512256: Success
1120. 731156023742988288: Success
1121. 730924654643314689: Success
1122. 730573383004487680: Success
1123. 730427201120833536: Success
1124. 730211855403241472: Success
1125. 730196704625098752: Success
1126. 729854734790754305: Success
1127. 729838605770891264: Success
1128. 729823566028484608: Success
1129. 729463711119904772: Success
1130. 729113531270991872: Success
1131. 728986383096946689: Success
1132. 728760639972315136: Success
1133. 728751179681943552: Success
1134. 728653952833728512: Success
1135. 728409960103686147: Success
1136. 728387165835677696: Success
1137. 728046963732717569: Success
1138. 728035342121635841: Success
1139. 728015554473250816: Success
1140. 727685679342333952: Success
1141. 727644517743104000: Success
1142. 727524757080539137: Success
1143. 727314416056803329: Success
1144. 727286334147182592: Success
1145. 727175381690781696: Success
1146. 727155742655025152: Success
1147. 726935089318363137: Success
1148. 726887082820554753: Success
1149. 726828223124897792: Success
1150. 726224900189511680: Success
1151. 725842289046749185: Success
1152. 725786712245440512: Success
1153. 725729321944506368: Success
1154. 725458796924002305: Success
1155. 724983749226668032: Success
1156. 724771698126512129: Success
1157. 724405726123311104: Success
1158. 724049859469295616: Success
1159. 724046343203856385: Success
1160. 724004602748780546: Success
1161. 723912936180330496: Success
1162. 723688335806480385: Success
1163. 723673163800948736: Success
1164. 723179728551723008: Success
1165. 722974582966214656: Success
1166. 722613351520608256: Success
1167. 721503162398597120: Success
1168. 721001180231503872: Success
1169. 720785406564900865: Success
1170. 720775346191278080: Success
1171. 720415127506415616: Success
1172. 720389942216527872: Success
1173. 720340705894408192: Success
1174. 720059472081784833: Success
1175. 720043174954147842: Success
1176. 719991154352222208: Success
1177. 719704490224398336: Success
1178. 719551379208073216: Success
1179. 719367763014393856: Success
1180. 719339463458033665: Success
1181. 719332531645071360: Success
1182. 718971898235854848: Success
1183. 718939241951195136: Success
1184. 718631497683582976: Success
1185. 718613305783398402: Success
1186. 718540630683709445: Success
1187. 718460005985447936: Success
1188. 718454725339934721: Success
1189. 718246886998687744: Success
1190. 718234618122661888: Success
1191. 717841801130979328: Success
1192. 717790033953034240: Success
1193. 717537687239008257: Success
1194. 717428917016076293: Success
1195. 717421804990701568: Success
1196. 717047459982213120: Success
1197. 717009362452090881: Success
1198. 716802964044845056: Success
1199. 716791146589110272: Success
1200. 716730379797970944: Success
1201. 716447146686459905: Success
1202. 716439118184652801: Success
1203. 716285507865542656: Success
1204. 716080869887381504: Success
1205. 715928423106027520: Success
1206. 715758151270801409: Success
1207. 715733265223708672: Success
1208. 715704790270025728: Success
1209. 715696743237730304: Success
1210. 715680795826982913: Success
1211. 715360349751484417: Success
1212. 715342466308784130: Success
1213. 715220193576927233: Success
1214. 715200624753819648: Success
1215. 715009755312439296: Success
1216. 714982300363173890: Success
1217. 714962719905021952: Success
1218. 714957620017307648: Success
1219. 714631576617938945: Success
1220. 714606013974974464: Success
1221. 714485234495041536: Success
1222. 714258258790387713: Success
1223. 714251586676113411: Success
1224. 714214115368108032: Success
1225. 714141408463036416: Success
1226. 713919462244790272: Success
1227. 713909862279876608: Success
1228. 713900603437621249: Success
1229. 713761197720473600: Success
1230. 713411074226274305: Success
1231. 713177543487135744: Success
1232. 713175907180089344: Success
1233. 712809025985978368: Success

1234. 712717840512598017: Success
1235. 712668654853337088: Success
1236. 712438159032893441: Success
1237. 712309440758808576: Success
1238. 712097430750289920: Success
1239. 712092745624633345: Success
1240. 712085617388212225: Success
1241. 712065007010385924: Success
1242. 711998809858043904: Success
1243. 711968124745228288: Success
1244. 711743778164514816: Success
1245. 711732680602345472: Success
1246. 711694788429553666: Success
1247. 711652651650457602: Success
1248. 711363825979756544: Success
1249. 711306686208872448: Success
1250. 711008018775851008: Success
1251. 710997087345876993: Success
1252. 710844581445812225: Success
1253. 710833117892898816: Success
1254. 710658690886586372: Success
1255. 710609963652087808: Success
1256. 710588934686908417: Success
1257. 710296729921429505: Success
1258. 710283270106132480: Success
1259. 710272297844797440: Success
1260. 710269109699739648: Success
1261. 710153181850935296: Success
1262. 710140971284037632: Success
1263. 710117014656950272: Success
1264. 709918798883774466: Success
1265. 709901256215666688: Success
1266. 709852847387627521: Success
1267. 709566166965075968: Success
1268. 709556954897764353: Success
1269. 709519240576036864: Success
1270. 709449600415961088: Success
1271. 709409458133323776: Success
1272. 709225125749587968: Success
1273. 709207347839836162: Success
1274. 709198395643068416: Success
1275. 709179584944730112: Success
1276. 709158332880297985: Success
1277. 709042156699303936: Success
1278. 708853462201716736: Success
1279. 708845821941387268: Success
1280. 708834316713893888: Success
1281. 708810915978854401: Success
1282. 708738143638450176: Success
1283. 708711088997666817: Success
1284. 708479650088034305: Success
1285. 708469915515297792: Success
1286. 708400866336894977: Success
1287. 708356463048204288: Success
1288. 708349470027751425: Success
1289. 708149363256774660: Success
1290. 708130923141795840: Success
1291. 708119489313951744: Success
1292. 708109389455101952: Success
1293. 708026248782585858: Success
1294. 707995814724026368: Success
1295. 707983188426153984: Success
1296. 707969809498152960: Success
1297. 707776935007539200: Success
1298. 707741517457260545: Success
1299. 707738799544082433: Success
1300. 707693576495472641: Success
1301. 707629649552134146: Success
1302. 707610948723478529: Success
1303. 707420581654872064: Success
1304. 707411934438625280: Success
1305. 707387676719185920: Success
1306. 707377100785885184: Success
1307. 707315916783140866: Success
1308. 707297311098011648: Success
1309. 707059547140169728: Success
1310. 707038192327901184: Success
1311. 707021089608753152: Success
1312. 707014260413456384: Success
1313. 706904523814649856: Success
1314. 706901761596989440: Success
1315. 706681918348251136: Success
1316. 706644897839910912: Success
1317. 706593038911545345: Success
1318. 706538006853918722: Success
1319. 706516534877929472: Success
1320. 706346369204748288: Success
1321. 706310011488698368: Success
1322. 706291001778950144: Success
1323. 706265994973601792: Success
1324. 706169069255446529: Success
1325. 706166467411222528: Success
1326. 706153300320784384: Success
1327. 705975130514706432: Success
1328. 705970349788291072: Success
1329. 705898680587526145: Success
1330. 705786532653883392: Success
1331. 705591895322394625: Success
1332. 705475953783398401: Success
1333. 705442520700944385: Success
1334. 705428427625635840: Success
1335. 705239209544720384: Success
1336. 705223444686888960: Success
1337. 705102439679201280: Success
1338. 705066031337840642: Success
1339. 704871453724954624: Success
1340. 704859558691414016: Success
1341. 704847917308362754: Success
1342. 704819833553219584: Success
1343. 704761120771465216: Success
1344. 704499785726889984: Success
1345. 704491224099647488: Success
1346. 704480331685040129: Success
1347. 704364645503647744: Success
1348. 704347321748819968: Success
1349. 704134088924532736: Success
1350. 704113298707505153: Success
1351. 704054845121142784: Success
1352. 703774238772166656: Success
1353. 703769065844768768: Success
1354. 703631701117943808: Success
1355. 703611486317502464: Success
1356. 703425003149250560: Success
1357. 703407252292673536: Success
1358. 703382836347330562: Success
1359. 703356393781329922: Success
1360. 703268521220972544: Success
1361. 703079050210877440: Success
1362. 703041949650034688: Success
1363. 702932127499816960: Success
1364. 702899151802126337: Success
1365. 702684942141153280: Success
1366. 702671118226825216: Success
1367. 702598099714314240: Success
1368. 702539513671897089: Success
1369. 702332542343577600: Success
1370. 702321140488925184: Success
1371. 702276748847800320: Success
1372. 702217446468493312: Success
1373. 701981390485725185: Success
1374. 701952816642965504: Success
1375. 701889187134500865: Success
1376. 701805642395348998: Success
1377. 701601587219795968: Success
1378. 701570477911896070: Success
1379. 701545186879471618: Success
1380. 701214700881756160: Success
1381. 700890391244103680: Success
1382. 700864154249383937: Success
1383. 700847567345688576: Success
1384. 700796979434098688: Success
1385. 700747788515020802: Success
1386. 700518061187723268: Success
1387. 700505138482569216: Success
1388. 700462010979500032: Success
1389. 700167517596164096: Success
1390. 700151421916807169: Success
1391. 700143752053182464: Success
1392. 700062718104104960: Success
1393. 700029284593901568: Success
1394. 700002074055016451: Success
1395. 699801817392291840: Success
1396. 699788877217865730: Success
1397. 699779630832685056: Success
1398. 699775878809702401: Success
1399. 699691744225525762: Success
1400. 699446877801091073: Success
1401. 699434518667751424: Success
1402. 699423671849451520: Success
1403. 699413908797464576: Success
1404. 699370870310113280: Success
1405. 699323444782047232: Success
1406. 699088579889332224: Success
1407. 699079609774645248: Success
1408. 699072405256409088: Success
1409. 699060279947165696: Success
1410. 699036661657767936: Success
1411. 698989035503689728: Success
1412. 698953797952008193: Success
1413. 698907974262222848: Success
1414. 698710712454139905: Success
1415. 698703483621523456: Success
1416. 698635131305795584: Success
1417. 698549713696649216: Success
1418. 698355670425473025: Success
1419. 698342080612007937: Success
1420. 698262614669991936: Success
1421. 698195409219559425: Success
1422. 698178924120031232: Success
1423. 697995514407682048: Success
1424. 697990423684476929: Success
1425. 697943111201378304: Success
1426. 697881462549430272: Success
1427. 697630435728322560: Success
1428. 697616773278015490: Success
1429. 697596423848730625: Success
1430. 697575480820686848: Success
1431. 697516214579523584: Success
1432. 697482927769255936: Success
1433. 697463031882764288: Success
1434. 697270446429966336: Success
1435. 697259378236399616: Success
1436. 697255105972801536: Success
1437. 697242256848379904: Success
1438. 696900204696625153: Success
1439. 696894894812565505: Success
1440. 696886256886657024: Success
1441. 696877980375769088: Success
1442. 696754882863349760: Success
1443. 696744641916489729: Success
1444. 696713835009417216: Success
1445. 696518437233913856: Success
1446. 696490539101908992: Success
1447. 696488710901260288: Success
1448. 696405997980676096: Success
1449. 696100768806522880: Success
1450. 695816827381944320: Success
1451. 695794761660297217: Success
1452. 695767669421768709: Success
1453. 695629776980148225: Success
1454. 695446424020918272: Success
1455. 695409464418041856: Success
1456. 695314793360662529: Success
1457. 695095422348574720: Success
1458. 695074328191332352: Success
1459. 695064344191721472: Success
1460. 695051054296211456: Success
1461. 694925794720792577: Success
1462. 694905863685980160: Success
1463. 694669722378485760: Success
1464. 694356675654983680: Success
1465. 694352839993344000: Success
1466. 694342028726001664: Success
1467. 694329668942569472: Success
1468. 694206574471057408: Success
1469. 694183373896572928: Success
1470. 694001791655137281: Success
1471. 693993230313091072: Success
1472. 693942351086120961: Success
1473. 693647888581312512: Success
1474. 693644216740769793: Success

1475. 693642232151285760: Success
1476. 693629975228977152: Success
1477. 693622659251335168: Success
1478. 693590843962331137: Success
1479. 693582294167244802: Success
1480. 693486665285931008: Success
1481. 693280720173801472: Success
1482. 693267061318012928: Success
1483. 693262851218264065: Success
1484. 693231807727280129: Success
1485. 693155686491000832: Success
1486. 693109034023534592: Success
1487. 693095443459342336: Success
1488. 692919143163629568: Success
1489. 692905862751522816: Success
1490. 692901601640583168: Success
1491. 692894228850999298: Success
1492. 692828166163931137: Success
1493. 692752401762250755: Success
1494. 692568918515392513: Success
1495. 692535307825213440: Success
1496. 692530551048294401: Success
1497. 692423280028966913: Success
1498. 692417313023332352: Success
1499. 692187005137076224: Success
1500. 692158366030913536: Success
1501. 692142790915014657: Success
1502. 692041934689402880: Success
1503. 692017291282812928: Success
1504. 691820333922455552: Success
1505. 691793053716221953: Success
1506. 691756958957883396: Success
1507. 691675652215414786: Success
1508. 691483041324204033: Success
1509. 691459709405118465: Success
1510. 691444869282295808: Success
1511. 691416866452082688: Success
1512. 691321916024623104: Success
1513. 691096613310316544: Success
1514. 691090071332753408: Success
1515. 690989312272396288: Success
1516. 690959652130045952: Success
1517. 690938899477221376: Success
1518. 690932576555528194: Success
1519. 690735892932222976: Success
1520. 690728923253055490: Success
1521. 690690673629138944: Success
1522. 690649993829576704: Success
1523. 690607260360429569: Success
1524. 690597161306841088: Success
1525. 690400367696297985: Success
1526. 690374419777196032: Success
1527. 690360449368465409: Success
1528. 690348396616552449: Success
1529. 690248561355657216: Success
1530. 690021994562220032: Success
1531. 690015576308211712: Success
1532. 690005060500217858: Success
1533. 689999384604450816: Success
1534. 689993469801164801: Success
1535. 689977555533848577: Success
1536. 689905486972461056: Success
1537. 689877686181715968: Success
1538. 689835978131935233: Success
1539. 689661964914655233: Success
1540. 689659372465688576: Success
1541. 689623661272240129: Success
1542. 689599056876867584: Success
1543. 689557536375177216: Success
1544. 689517482558820352: Success
1545. 689289219123089408: Success
1546. 689283819090870273: Success
1547. 689280876073582592: Success
1548. 689275259254616065: Success
1549. 689255633275777024: Success
1550. 689154315265683456: Success
1551. 689143371370250240: Success
1552. 688916208532455424: Success
1553. 688908934925697024: Success
1554. 688898160958271489: Success
1555. 688894073864884227: Success
1556. 688828561667567616: Success
1557. 688804835492233216: Success
1558. 688789766343622656: Success
1559. 688547210804498433: Success
1560. 688519176466644993: Success
1561. 688385280030670848: Success
1562. 688211956440801280: Success
1563. 688179443353796608: Success
1564. 688116655151435777: Success
1565. 688064179421470721: Success
1566. 687841446767013888: Success
1567. 687826841265172480: Success
1568. 687818504314159109: Success
1569. 687807801670897665: Success
1570. 687732144991551489: Success
1571. 687704180304273409: Success
1572. 687664829264453632: Success
1573. 687494652870668288: Success
1574. 687480748861947905: Success
1575. 687476254459715584: Success
1576. 687460506001633280: Success
1577. 687399393394311168: Success
1578. 687317306314240000: Success
1579. 687312378585812992: Success
1580. 687127927494963200: Success
1581. 687124485711986689: Success
1582. 687109925361856513: Success
1583. 687102708889812993: Success
1584. 687096057537363968: Success
1585. 686947101016735744: Success
1586. 686760001961103360: Success
1587. 686749460672679938: Success
1588. 686730991906516992: Success
1589. 686683045143953408: Success
1590. 686618349602762752: Success
1591. 686606069955735556: Success
1592. 686394059078897668: Success
1593. 686386521809772549: Success
1594. 686377065986265092: Success
1595. 686358356425093120: Success
1596. 686286779679375361: Success
1597. 686050296934563840: Success
1598. 686035780142297088: Success
1599. 686034024800862208: Success
1600. 686007916130873345: Success
1601. 686003207160610816: Success
1602. 685973236358713344: Success
1603. 685943807276412928: Success
1604. 685906723014619143: Success
1605. 685681090388975616: Success
1606. 685667379192414208: Success
1607. 685663452032069632: Success
1608. 685641971164143616: Success
1609. 685547936038666240: Success
1610. 685532292383666176: Success
1611. 685325112850124800: Success
1612. 685321586178670592: Success
1613. 685315239903100929: Success
1614. 685307451701334016: Success
1615. 685268753634967552: Success
1616. 685198997565345792: Success
1617. 685169283572338688: Success
1618. 684969860808454144: Success
1619. 684959798585110529: Success
1620. 684940049151070208: Success
1621. 684926975086034944: Success
1622. 684914660081053696: Success
1623. 684902183876321280: Success
1624. 684880619965411328: Success
1625. 684830982659280897: Success
1626. 684800227459624960: Success
1627. 684594889858887680: Success
1628. 684588130326986752: Success
1629. 684567543613382656: Success
1630. 684538444857667585: Success
1631. 684481074559381504: Success
1632. 684460069371654144: Success
1633. 684241637099323392: Success
1634. 684225744407494656: Success
1635. 684222868335505415: Success
1636. 684200372118904832: Success
1637. 684195085588783105: Success
1638. 684188786104872960: Success
1639. 684177701129875456: Success
1640. 684147889187209216: Success
1641. 684122891630342144: Success
1642. 684097758874210310: Success
1643. 683857920510050305: Success
1644. 683852578183077888: Success
1645. 683849932751646720: Success
1646. 683834909291606017: Success
1647. 683828599284170753: Success
1648. 683773439333797890: Success
1649. 683742671509258241: Success
1650. 683515932363329536: Success
1651. 683498322573824003: Success
1652. 683481228088049664: Success
1653. 683462770029932544: Success
1654. 683449695444799489: Success
1655. 683391852557561860: Success
1656. 683357973142474752: Success
1657. 683142553609318400: Success
1658. 683111407806746624: Success
1659. 683098815881154561: Success
1660. 683078886620553216: Success
1661. 683030066213818368: Success
1662. 682962037429899265: Success
1663. 682808988178739200: Success
1664. 682788441537560576: Success
1665. 682750546109968385: Success
1666. 682697186228989953: Success
1667. 682662431982772225: Success
1668. 682638830361513985: Success
1669. 682429480204398592: Success
1670. 682406705142087680: Success
1671. 682393905736888321: Success
1672. 682389078323662849: Success
1673. 682303737705140231: Success
1674. 682259524040966145: Success
1675. 682242692827447297: Success
1676. 682088079302213632: Success
1677. 682059653698686977: Success
1678. 682047327939461121: Success
1679. 682032003584274432: Success
1680. 682003177596559360: Success
1681. 681981167097122816: Success
1682. 681891461017812993: Success
1683. 681694085539872773: Success
1684. 681679526984871937: Success
1685. 681654059175129088: Success
1686. 681610798867845120: Success
1687. 681579835668455424: Success
1688. 681523177663676416: Success
1689. 681340665377193984: Success
1690. 681339448655802368: Success
1691. 681320187870711809: Success
1692. 681302363064414209: Success
1693. 681297372102656000: Success
1694. 681281657291280384: Success
1695. 681261549936340994: Success
1696. 681242418453299201: Success
1697. 681231109724700672: Success
1698. 681193455364796417: Success
1699. 680970795137544192: Success
1700. 680959110691590145: Success
1701. 680940246314430465: Success
1702. 680934982542561280: Success
1703. 680913438424612864: Success
1704. 680889648562991104: Success
1705. 680836378243002368: Success
1706. 680805554198020098: Success
1707. 680801747103793152: Success
1708. 680798457301471234: Success
1709. 680609293079592961: Success
1710. 680583894916304897: Success
1711. 680497766108381184: Success
1712. 680494726643068929: Success
1713. 680473011644985345: Success
1714. 680440374763077632: Success
1715. 680221482581123072: Success

1716. 680206703334408192: Success
1717. 680191257256136705: Success
1718. 680176173301628928: Success
1719. 680161097740095489: Success
1720. 680145970311643136: Success
1721. 680130881361686529: Success
1722. 680115823365742593: Success
1723. 680100725817409536: Success
1724. 680085611152338944: Success
1725. 680070545539371008: Success
1726. 680055455951884288: Success
1727. 679877062409191424: Success
1728. 679872969355714560: Success
1729. 679862121895714818: Success
1730. 679854723806179328: Success
1731. 679844490799091713: Success
1732. 679828447187857408: Success
1733. 679777920601223168: Success
1734. 679736210798047232: Success
1735. 679729593985699840: Success
1736. 679722016581222400: Success
1737. 679530280114372609: Success
1738. 679527802031484928: Success
1739. 679511351870550016: Success
1740. 679503373272485890: Success
1741. 679475951516934144: Success
1742. 679462823135686656: Success
1743. 679405845277462528: Success
1744. 679158373988876288: Success
1745. 679148763231985668: Success
1746. 679132435750195208: Success
1747. 679111216690831360: Success
1748. 679062614270468097: Success
1749. 679047485189439488: Success
1750. 679001094530465792: Success
1751. 678991772295516161: Success
1752. 678969228704284672: Success
1753. 678800283649069056: Success
1754. 678798276842360832: Success
1755. 678774928607469569: Success
1756. 678767140346941444: Success
1757. 678764513869611008: Success
1758. 678755239630127104: Success
1759. 678740035362037760: Success
1760. 678708137298427904: Success
1761. 678675843183484930: Success
1762. 678643457146150913: Success
1763. 678446151570427904: Success
1764. 678424312106393600: Success
1765. 678410210315247616: Success
1766. 678399652199309312: Success
1767. 678396796259975168: Success
1768. 678389028614488064: Success
1769. 678380236862578688: Success
1770. 678341075375947776: Success
1771. 678334497360859136: Success
1772. 678278586130948096: Success
1773. 678255464182861824: Success
1774. 678023323247357953: Success
1775. 678021115718029313: Success
1776. 677961670166224897: Success
1777. 677918531514703872: Success
1778. 677895101218201600: Success
1779. 677716515794329600: Success
1780. 677700003327029250: Success
1781. 677698403548192770: Success
1782. 677687604918272002: Success
1783. 677673981332312066: Success
1784. 677662372920729601: Success
1785. 677644091929329666: Success
1786. 677573743309385728: Success
1787. 677565715327688705: Success
1788. 677557565589463040: Success
1789. 677547928504967168: Success
1790. 677530072887205888: Success
1791. 677335745548390400: Success
1792. 677334615166730240: Success
1793. 677331501395156992: Success
1794. 677328882937298944: Success
1795. 677314812125323265: Success
1796. 677301033169788928: Success
1797. 677269281705472000: Success
1798. 677228873407442944: Success
1799. 677187300187611136: Success
1800. 676975532580409345: Success
1801. 676957860086095872: Success
1802. 676949632774234114: Success
1803. 676948236477857792: Success
1804. 676946864479084545: Success
1805. 676942428000112642: Success
1806. 676936541936185344: Success
1807. 676916996760600576: Success
1808. 676897532954456065: Success
1809. 676864501615042560: Success
1810. 676821958043033607: Success
1811. 676819651066732545: Success
1812. 676811746707918848: Success
1813. 676776431406465024: Success
1814. 676617503762681856: Success
1815. 676613908052996102: Success
1816. 676606785097199616: Success
1817. 676603393314578432: Success
1818. 676593408224403456: Success
1819. 676590572941893632: Success
1820. 676588346097852417: Success
1821. 676582956622721024: Success
1822. 676575501977128964: Success
1823. 676533798876651520: Success
1824. 676496375194980353: Success
1825. 676470639084101634: Success
1826. 676440007570247681: Success
1827. 676430933382295552: Success
1828. 676263575653122048: Success
1829. 676237365392908289: Success
1830. 676219687039057920: Success
1831. 676215927814406144: Success
1832. 676191832485810177: Success
1833. 676146341966438401: Success
1834. 676121918416756736: Success
1835. 676101918813499392: Success
1836. 676098748976615425: Success
1837. 676089483918516224: Success
1838. 675898130735476737: Success
1839. 675891555769696257: Success
1840. 675888385639251968: Success
1841. 675878199931371520: Success
1842. 675870721063669760: Success
1843. 675853064436391936: Success
1844. 675849018447167488: Success
1845. 675845657354215424: Success
1846. 675822767435051008: Success
1847. 675820929667219457: Success
1848. 675798442703122432: Success
1849. 675781562965868544: Success
1850. 675740360753160193: Success
1851. 675710890956750848: Success
1852. 675707330206547968: Success
1853. 675706639471788032: Success
1854. 675534494439489536: Success
1855. 675531475945709568: Success
1856. 675522403582218240: Success
1857. 675517828909424640: Success
1858. 675501075957489664: Success
1859. 675497103322386432: Success
1860. 675489971617296384: Success
1861. 675483430902214656: Success
1862. 675432746517426176: Success
1863. 675372240448454658: Success
1864. 675362609739206656: Success
1865. 675354435921575936: Success
1866. 675349384339542016: Success
1867. 675334060156301312: Success
1868. 675166823650848770: Success
1869. 675153376133427200: Success
1870. 675149409102012420: Success
1871. 675147105808306176: Success
1872. 675146535592706048: Success
1873. 675145476954566656: Success
1874. 675135153782571009: Success
1875. 675113801096802304: Success
1876. 675111688094527488: Success
1877. 675109292475830276: Success
1878. 675047298674663426: Success
1879. 675015141583413248: Success
1880. 675006312288268288: Success
1881. 675003128568291329: Success
1882. 674999807681908736: Success
1883. 674805413498527744: Success
1884. 674800520222154752: Success
1885. 674793399141146624: Success
1886. 674790488185167872: Success
1887. 674788554665512960: Success
1888. 674781762103414784: Success
1889. 674774481756377088: Success
1890. 674767892831932416: Success
1891. 674764817387900928: Success
1892. 674754018082705410: Success
1893. 674752233200820224: Success
1894. 674743008475090944: Success
1895. 674742531037511680: Success
1896. 674739953134403584: Success
1897. 674737130913071104: Success
1898. 674690135443775488: Success
1899. 674670581682434048: Success
1900. 674664755118911488: Success
1901. 674646392044941312: Success
1902. 674644256330530816: Success
1903. 674638615994089473: Success
1904. 674632714662858753: Success
1905. 674606911342424069: Success
1906. 674468880899788800: Success
1907. 674447403907457024: Success
1908. 674436901579923456: Success
1909. 674422304705744896: Success
1910. 674416750885273600: Success
1911. 674410619106390016: Success
1912. 674394782723014656: Success
1913. 674372068062928900: Success
1914. 674330906434379776: Success
1915. 674318007229923329: Success
1916. 674307341513269249: Success
1917. 674291837063053312: Success
1918. 674271431610523648: Success
1919. 674269164442398721: Success
1920. 674265582246694913: Success
1921. 674262580978937856: Success
1922. 674255168825880576: Success
1923. 674082852460433408: Success
1924. 674075285688614912: Success
1925. 674063288070742018: Success
1926. 674053186244734976: Success
1927. 674051556661161984: Success
1928. 674045139690631169: Success
1929. 674042553264685056: Success
1930. 674038233588723717: Success
1931. 674036086168010753: Success
1932. 674024893172875264: Success
1933. 674019345211760640: Success
1934. 674014384960745472: Success
1935. 674008982932058114: Success
1936. 673956914389192708: Success
1937. 673919437611909120: Success
1938. 673906403526995968: Success
1939. 673887867907739649: Success
1940. 673716320723169284: Success
1941. 673715861853720576: Success
1942. 673711475735838725: Success
1943. 673709992831262724: Success
1944. 673708611235921920: Success
1945. 673707060090052608: Success
1946. 673705679337693185: Success
1947. 673700254269775872: Success
1948. 673697980713705472: Success
1949. 673689733134946305: Success
1950. 673688752737402881: Success
1951. 673686845050527744: Success
1952. 673680198160809984: Success
1953. 673662677122719744: Success
1954. 673656262056419329: Success
1955. 673636718965334016: Success
1956. 673612854080196609: Success

1957. 673583129559498752: Success
1958. 673580926094458881: Success
1959. 673576835670777856: Success
1960. 673363615379013632: Success
1961. 673359818736984064: Success
1962. 673355879178194945: Success
1963. 673352124999274496: Success
1964. 673350198937153538: Success
1965. 673345638550134785: Success
1966. 673343217010679808: Success
1967. 673342308415348736: Success
1968. 673320132811366400: Success
1969. 673317986296586240: Success
1970. 673295268553605120: Success
1971. 673270968295534593: Success
1972. 673240798075449344: Success
1973. 673213039743795200: Success
1974. 673148804208660480: Success
1975. 672997845381865473: Success
1976. 672995267319328768: Success
1977. 672988786805112832: Success
1978. 672984142909456390: Success
1979. 672980819271634944: Success
1980. 672975131468300288: Success
1981. 672970152493887488: Success
1982. 672968025906282496: Success
1983. 672964561327235073: Success
1984. 672902681409806336: Success
1985. 672898206762672129: Success
1986. 672884426393653248: Success
1987. 672877615439593473: Success
1988. 672834301050937345: Success
1989. 672828477930868736: Success
1990. 672640509974827008: Success
1991. 672622327801233409: Success
1992. 672614745925664768: Success
1993. 672609152938721280: Success
1994. 672604026190569472: Success
1995. 672594978741354496: Success
1996. 672591762242805761: Success
1997. 672591271085670400: Success
1998. 672538107540070400: Success
1999. 672523490734551040: Success
2000. 672488522314567680: Success
2001. 672482722825261057: Success
2002. 672481316919734272: Success
2003. 672475084225949696: Success
2004. 672466075045466113: Success
2005. 672272411274932228: Success
2006. 672267570918129665: Success
2007. 672264251789176834: Success
2008. 672256522047614977: Success
2009. 672254177670729728: Success
2010. 672248013293752320: Success
2011. 672245253877968896: Success
2012. 672239279297454080: Success
2013. 672231046314901505: Success
2014. 672222792075620352: Success
2015. 672205392827572224: Success
2016. 672169685991993344: Success
2017. 672160042234327040: Success
2018. 672139350159835138: Success
2019. 672125275208069120: Success
2020. 672095186491711488: Success
2021. 672082170312290304: Success
2022. 672068090318987265: Success
2023. 671896809300709376: Success
2024. 671891728106971137: Success
2025. 671882082306625538: Success
2026. 671879137494245376: Success
2027. 671874878652489728: Success
2028. 671866342182637568: Success
2029. 671855973984772097: Success
2030. 671789708968640512: Success
2031. 671768281401958400: Success
2032. 671763349865160704: Success
2033. 671744970634719232: Success
2034. 671743150407421952: Success
2035. 671735591348891648: Success
2036. 671729906628341761: Success
2037. 671561002136281088: Success
2038. 671550332464455680: Success
2039. 671547767500775424: Success
2040. 671544874165002241: Success
2041. 671542985629241344: Success
2042. 671538301157904385: Success
2043. 671536543010570240: Success
2044. 671533943490011136: Success
2045. 671528761649688577: Success
2046. 671520732782923777: Success
2047. 671518598289059840: Success
2048. 671511350426865664: Success
2049. 671504605491109889: Success
2050. 671497587707535361: Success
2051. 671488513339211776: Success
2052. 671486386088865792: Success
2053. 671485057807351808: Success
2054. 671390180817915904: Success
2055. 671362598324076544: Success
2056. 671357843010908160: Success
2057. 671355857343524864: Success
2058. 671347597085433856: Success
2059. 671186162933985280: Success
2060. 671182547775299584: Success
2061. 671166507850801152: Success
2062. 671163268581498880: Success
2063. 671159727754231808: Success
2064. 671154572044468225: Success
2065. 671151324042559489: Success
2066. 671147085991960577: Success
2067. 671141549288370177: Success
2068. 671138694582165504: Success
2069. 671134062904504320: Success
2070. 671122204919246848: Success
2071. 671115716440031232: Success
2072. 671109016219725825: Success
2073. 670995969505435648: Success
2074. 670842764863651840: Success
2075. 670840546554966016: Success
2076. 670838202509447168: Success
2077. 670833812859932673: Success
2078. 670832455012716544: Success
2079. 670826280409919488: Success
2080. 670823764196741120: Success
2081. 670822709593571328: Success
2082. 670815497391357952: Success
2083. 670811965569282048: Success
2084. 670807719151067136: Success
2085. 670804601705242624: Success
2086. 670803562457407488: Success
2087. 670797304698376195: Success
2088. 670792680469889025: Success
2089. 670789397210615808: Success
2090. 670786190031921152: Success
2091. 670783437142401025: Success
2092. 670782429121134593: Success
2093. 670780561024270336: Success
2094. 670778058496974848: Success
2095. 670764103623966721: Success
2096. 670755717859713024: Success
2097. 670733412878163972: Success
2098. 670727704916926465: Success
2099. 670717338665226240: Success
2100. 670704688707301377: Success
2101. 670691627984359425: Success
2102. 670679630144274432: Success
2103. 670676092097810432: Success
2104. 670668383499735048: Success
2105. 670474236058800128: Success
2106. 670468609693655041: Success
2107. 670465786746662913: Success
2108. 670452855871037440: Success
2109. 670449342516494336: Success
2110. 670444955656130560: Success
2111. 670442337873600512: Success
2112. 670435821946826752: Success
2113. 670434127938719744: Success
2114. 670433248821026816: Success
2115. 670428280563085312: Success
2116. 670427002554466305: Success
2117. 670421925039075328: Success
2118. 670420569653809152: Success
2119. 670417414769758208: Success
2120. 670411370698022913: Success
2121. 670408998013820928: Success
2122. 670403879788544000: Success
2123. 670385711116361728: Success
2124. 670374371102445568: Success
2125. 670361874861563904: Success
2126. 670338931251150849: Success
2127. 670319130621435904: Success
2128. 670303360680108032: Success
2129. 670290420111441920: Success
2130. 670093938074779648: Success
2131. 670086499208155136: Success
2132. 670079681849372674: Success
2133. 670073503555706880: Success
2134. 670069087419133954: Success
2135. 670061506722140161: Success
2136. 670055038660800512: Success
2137. 670046952931721218: Success
2138. 670040295598354432: Success
2139. 670037189829525505: Success
2140. 670003130994700288: Success
2141. 669993076832759809: Success
2142. 669972011175813120: Success
2143. 669970042633789440: Success
2144. 669942763794931712: Success
2145. 669926384437997569: Success
2146. 669923323644657664: Success
2147. 669753178989142016: Success
2148. 669749430875258880: Success
2149. 669684865554620416: Success
2150. 669683899023405056: Success
2151. 669682095984410625: Success
2152. 669680153564442624: Success
2153. 669661792646373376: Success
2154. 669625907762618368: Success
2155. 669603084620980224: Success
2156. 669597912108789760: Success
2157. 669583744538451968: Success
2158. 669573570759163904: Success
2159. 669571471778410496: Success
2160. 669567591774625800: Success
2161. 669564461267722241: Success
2162. 669393256313184256: Success
2163. 669375718304980992: Success
2164. 669371483794317312: Success
2165. 669367896104181761: Success
2166. 669363888236994561: Success
2167. 669359674819481600: Success
2168. 669354382627049472: Success
2169. 669353438988365824: Success
2170. 669351434509529089: Success
2171. 669328503091937280: Success
2172. 669327207240699904: Success
2173. 669324657376567296: Success
2174. 669216679721873412: Success
2175. 669214165781868544: Success
2176. 669203728096960512: Success
2177. 669037058363662336: Success
2178. 669015743032369152: Success
2179. 669006782128353280: Success
2180. 669000397445533696: Success
2181. 668994913074286592: Success
2182. 668992363537309700: Success
2183. 668989615043424256: Success
2184. 668988183816871936: Success
2185. 668986018524233728: Success
2186. 668981893510119424: Success
2187. 668979806671884288: Success
2188. 668975677807423489: Success
2189. 668967877119254528: Success
2190. 668960084974809088: Success
2191. 668955713004314625: Success
2192. 668932921458302977: Success
2193. 668902994700836864: Success
2194. 668892474547511297: Success
2195. 668872652652679168: Success
2196. 668852170888998912: Success
2197. 668826086256599040: Success

2198. 668815180734689280: Success
2199. 668779399630725120: Success
2200. 668655139528511488: Success
2201. 668645506898350081: Success
2202. 668643542311546881: Success
2203. 668641109086707712: Success
2204. 668636665813057536: Success
2205. 668633411083464705: Success
2206. 668631377374486528: Success
2207. 668627278264475648: Success
2208. 668625577880875008: Success
2209. 668623201287675904: Success
2210. 668620235289837568: Success
2211. 668614819948453888: Success
2212. 668587383441514497: Success
2213. 668567822092664832: Success
2214. 668544745690562560: Success
2215. 668542336805281792: Success
2216. 668537837512433665: Success
2217. 668528771708952576: Success
2218. 668507509523615744: Success
2219. 668496999348633600: Success
2220. 668484198282485761: Success
2221. 668480044826800133: Success
2222. 668466899341221888: Success
2223. 668297328638447616: Success
2224. 668291999406125056: Success
2225. 668286279830867968: Success
2226. 668274247790391296: Success
2227. 668268907921326080: Success
2228. 668256321989451776: Success
2229. 668248472370458624: Success
2230. 668237644992782336: Success
2231. 668226093875376128: Success
2232. 668221241640230912: Success
2233. 668204964695683073: Success
2234. 668190681446379520: Success
2235. 668171859951755264: Success
2236. 668154635664932864: Success
2237. 668142349051129856: Success
2238. 668113020489474048: Success
2239. 667937095915278337: Success
2240. 667924896115245057: Success
2241. 667915453470232577: Success
2242. 667911425562669056: Success
2243. 667902449697558528: Success
2244. 667886921285246976: Success
2245. 667885044254572545: Success
2246. 667878741721415682: Success
2247. 667873844930215936: Success
2248. 667866724293877760: Success
2249. 667861340749471744: Success
2250. 667832474953625600: Success
2251. 667806454573760512: Success
2252. 667801013445750784: Success
2253. 667793409583771648: Success
2254. 667782464991965184: Success
2255. 667773195014021121: Success
2256. 667766675769573376: Success
2257. 667728196545200128: Success
2258. 667724302356258817: Success
2259. 667550904950915073: Success
2260. 667550882905632768: Success
2261. 667549055577362432: Success
2262. 667546741521195010: Success
2263. 667544320556335104: Success
2264. 667538891197542400: Success
2265. 667534815156183040: Success
2266. 667530908589760512: Success
2267. 667524857454854144: Success
2268. 667517642048163840: Success
2269. 667509364010450944: Success
2270. 667502640335572993: Success
2271. 667495797102141441: Success
2272. 667491009379606528: Success
2273. 667470559035432960: Success
2274. 667455448082227200: Success
2275. 667453023279554560: Success
2276. 667443425659232256: Success
2277. 667437278097252352: Success
2278. 667435689202614272: Success
2279. 667405339315146752: Success
2280. 667393430834667520: Success
2281. 667369227918143488: Success
2282. 667211855547486208: Success
2283. 667200525029539841: Success
2284. 667192066997374976: Success
2285. 667188689915760640: Success
2286. 667182792070062081: Success
2287. 667177989038297088: Success
2288. 667176164155375616: Success
2289. 667174963120574464: Success
2290. 667171260800061440: Success
2291. 667165590075940865: Success
2292. 667160273090932737: Success
2293. 667152164079423490: Success
2294. 667138269671505920: Success
2295. 667119796878725120: Success
2296. 667090893657276420: Success
2297. 667073648344346624: Success
2298. 667070482143944705: Success
2299. 667065535570550784: Success
2300. 667062181243039745: Success
2301. 667044094246576128: Success
2302. 667012601033924608: Success
2303. 666996132027977728: Success
2304. 666983947667116034: Success
2305. 666837028449972224: Success
2306. 666835007768551424: Success
2307. 666826780179869698: Success
2308. 666817836334096384: Success
2309. 666804364988780544: Success
2310. 666786068205871104: Success
2311. 666781792255496192: Success
2312. 666776908487630848: Success
2313. 666739327293083650: Success
2314. 666701168228331520: Success
2315. 666691418707132416: Success
2316. 666649482315059201: Success
2317. 666644823164719104: Success
2318. 666454714377183233: Success
2319. 666447344410484738: Success
2320. 666437273139982337: Success
2321. 666435652385423360: Success
2322. 666430724426358785: Success
2323. 666428276349472768: Success
2324. 666421158376562688: Success
2325. 666418789513326592: Success
2326. 666411507551481857: Success
2327. 666407126856765440: Success
2328. 666396247373291520: Success
2329. 666373753744588802: Success
2330. 666362758909284353: Success
2331. 666353288456101888: Success
2332. 666345417576210432: Success
2333. 666337882303524864: Success
2334. 666293911632134144: Success
2335. 666287406224695296: Success
2336. 666273097616637952: Success
2337. 666268910803644416: Success
2338. 666104133288665088: Success
2339. 666102155909144576: Success
2340. 666099513787052032: Success
2341. 666094000022159362: Success
2342. 666082916733198337: Success
2343. 666073100786774016: Success
2344. 666071193221509120: Success
2345. 666063827256086533: Success
2346. 666058600524156928: Success
2347. 666057090499244032: Success
2348. 666055525042405380: Success
2349. 666051853826850816: Success
2350. 666050758794694657: Success
2351. 666049248165822465: Success
2352. 666044226329800704: Success
2353. 666033412701032449: Success
2354. 666029285002620928: Success
2355. 666020888022790149: Success
3597.9562435150146seconds to complete

In [8]:
len(success_tweets)

2345

Creating a dataframe from the json data

In [9]:

start=time.time()

json_list=[]
tweet_id=[]
favorite_count=[]
retweet_count=[]

with open("tweet_json.txt") as file:
    json_txt= file.readlines()

for entry in json_txt:
    json_entry = json.loads(entry)
    json_list.append(json_entry)
    tweet_id.append(json_entry['id'])
    favorite_count.append(json_entry['favorite_count'])
    retweet_count.append(json_entry['retweet_count'])
    
end=time.time()
print(str(end-start)+ "seconds to complete")

0.871535062789917seconds to complete

In [10]:
df_3=pd.DataFrame({'tweet_id':tweet_id,
                "favorite_count": favorite_count,
                'retweet_count': retweet_count})

## Assess

### df_1 : twitter-archive-enhanced.csv

In [11]:
df_1.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None

In [12]:
df_1.source.value_counts()

<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>     2221
<a href="http://vine.co" rel="nofollow">Vine - Make a Scene</a>                          91
<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>                       33
<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>      11
Name: source, dtype: int64

**Issues:**
- source is in html format and not text
- retweets and replies columns have a lot of Nan
- attributes like doggo, pupper, floofer, puppo need to be set as dummies

In [13]:
df_1.shape

(2356, 17)

In [14]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

**Issues:**
* Missing values
    - expanded_urls 
    - in_reply_to_status_id & in_reply_to_user_id
    - retweeted_status_id, retweeted_status_user_id & retweeted_status_timestamp 

* dtypes
    - tweet_id: int64
    - in_reply_to_status_id: float64
    - in_reply_to_user_id: float64
    - retweeted_status_id: float64
    - retweeted_status_user_id: float64

In [15]:
df_1.timestamp[666], type(df_1.timestamp[0])

('2016-10-24 15:53:19 +0000', str)

In [16]:
type((df_1.retweeted_status_timestamp[df_1.retweeted_status_timestamp.notna()].tolist())[0])

str

**Issue:**
- timestamp is a string
- retweeted_status_timestamp is a string

In [17]:
df_1.expanded_urls.sample(10)

259     https://twitter.com/dog_rates/status/843235543...
966     https://twitter.com/dog_rates/status/750383411...
1509    https://twitter.com/dog_rates/status/691459709...
1543    https://twitter.com/dog_rates/status/689557536...
2110    https://twitter.com/dog_rates/status/670444955...
1252    https://twitter.com/dog_rates/status/710844581...
882     https://twitter.com/dog_rates/status/760290219...
1998    https://twitter.com/dog_rates/status/672538107...
959     https://twitter.com/dog_rates/status/751251247...
584     https://twitter.com/dog_rates/status/800141422...
Name: expanded_urls, dtype: object

Issues:
- expanded_urls have multiple urls for some entries
- expanded_urls have whitespace for some entries

In [18]:
pd.set_option('display.max_colwidth', -1)
df_1.text.sample(10)

345     This is Emanuel. He's a h*ckin rare doggo. Dwells in a semi-urban environment. Round features make him extra collectible. 12/10 would so pet https://t.co/k9bzgyVdUT
1452    If you are aware of who is making these please let me know. 13/10 vroom vroom https://t.co/U0D1sbIDrG
350     This is Dutch. He dressed up as his favorite emoji for Valentine's Day. I've got heart eyes for his heart eyes. 13/10 https://t.co/BCbmFYLrse
1109    This is Terry. The harder you hug him the farther his tongue sticks out. 10/10 magical af https://t.co/RFToQQI8fJ
519     This is Phil. He's a father. A very good father too. 13/10 everybody loves Phil https://t.co/9p6ECXJMMu
1582    This is Baxter. He looks like a fun dog. Prefers action shots. 11/10 the last one is impeccable https://t.co/LHcH1yhhIb
52      This is Koko. Her owner, inspired by Barney, recently built a cart for her to use during walks if she got tired. 13/10 rest easy Koko https://t.co/zeDpnsKX7w
993     This is one of the most reckless puppers I've ever seen. How she got a license in the first place is beyond me. 6/10 https://t.co/z5bAdtn9kd
1061    This is Theodore. He just saw an adult wearing crocs. Did him a frighten. Lost other ear back in nam. 12/10 hero af https://t.co/O4iw9NlLaQ
1021    Meet Abby. She's incredibly distracting. Just wants to help steer. Hazardous af. Still 12/10 would pet while driving https://t.co/gLbLiZtwsp
Name: text, dtype: object

In [19]:
pd.reset_option('display.max_colwidth')

**Issues:**
- Some of the tweet texts have shortened urls included

In [20]:
df_1.describe()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,retweeted_status_id,retweeted_status_user_id,rating_numerator,rating_denominator
count,2.356000e+03,7.800000e+01,7.800000e+01,1.810000e+02,1.810000e+02,2356.000000,2356.000000
mean,7.427716e+17,7.455079e+17,2.014171e+16,7.720400e+17,1.241698e+16,13.126486,10.455433
std,6.856705e+16,7.582492e+16,1.252797e+17,6.236928e+16,9.599254e+16,45.876648,6.745237
min,6.660209e+17,6.658147e+17,1.185634e+07,6.661041e+17,7.832140e+05,0.000000,0.000000
25%,6.783989e+17,6.757419e+17,3.086374e+08,7.186315e+17,4.196984e+09,10.000000,10.000000
50%,7.196279e+17,7.038708e+17,4.196984e+09,7.804657e+17,4.196984e+09,11.000000,10.000000
75%,7.993373e+17,8.257804e+17,4.196984e+09,8.203146e+17,4.196984e+09,12.000000,10.000000
max,8.924206e+17,8.862664e+17,8.405479e+17,8.874740e+17,7.874618e+17,1776.000000,170.000000

In [21]:
df_1.rating_numerator.value_counts()

12      558
11      464
10      461
13      351
9       158
8       102
7        55
14       54
5        37
6        32
3        19
4        17
1         9
2         9
420       2
0         2
15        2
75        2
80        1
20        1
24        1
26        1
44        1
50        1
60        1
165       1
84        1
88        1
144       1
182       1
143       1
666       1
960       1
1776      1
17        1
27        1
45        1
99        1
121       1
204       1
Name: rating_numerator, dtype: int64

In [22]:
df_1.rating_denominator.value_counts()

10     2333
11        3
50        3
80        2
20        2
2         1
16        1
40        1
70        1
15        1
90        1
110       1
120       1
130       1
150       1
170       1
7         1
0         1
Name: rating_denominator, dtype: int64

Issues:
- rating_numerator has min value as 0 and high maximum value
    - checking value_counts reveals a good picture of range and outliers
- rating_denominator has min value as 0 and high maximum value
    - checking value_counts reveals less issues with denominator but we can still see some outliers

In [23]:
df_1.duplicated().sum(), df_1.tweet_id.duplicated().sum(), df_1.text.duplicated().sum()

(0, 0, 0)

In [24]:
df_1.timestamp.duplicated().sum(), df_1.expanded_urls.duplicated().sum()

(0, 137)

### df_2 : image-predictions.tsv

In [25]:
df_2.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

**Issues:**
- inconsistent alphabetic casing in p1, p2, p3
- p1, p2, p3 contain "_" instead of space
- non descriptive column names
- the table seems to be secondary ie supplement to the primary data assessed as df_1
- breed of dog needs to be concluded

In [26]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id    2075 non-null int64
jpg_url     2075 non-null object
img_num     2075 non-null int64
p1          2075 non-null object
p1_conf     2075 non-null float64
p1_dog      2075 non-null bool
p2          2075 non-null object
p2_conf     2075 non-null float64
p2_dog      2075 non-null bool
p3          2075 non-null object
p3_conf     2075 non-null float64
p3_dog      2075 non-null bool
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB

**Issues:**

- tweet_id is of int64 dtype

In [27]:
df_2.describe()

           tweet_id      img_num      p1_conf       p2_conf       p3_conf
count  2.075000e+03  2075.000000  2075.000000  2.075000e+03  2.075000e+03
mean   7.384514e+17     1.203855     0.594548  1.345886e-01  6.032417e-02
std    6.785203e+16     0.561875     0.271174  1.006657e-01  5.090593e-02
min    6.660209e+17     1.000000     0.044333  1.011300e-08  1.740170e-10
25%    6.764835e+17     1.000000     0.364412  5.388625e-02  1.622240e-02
50%    7.119988e+17     1.000000     0.588230  1.181810e-01  4.944380e-02
75%    7.932034e+17     1.000000     0.843855  1.955655e-01  9.180755e-02
max    8.924206e+17     4.000000     1.000000  4.880140e-01  2.734190e-01

In [28]:
df_2.duplicated().sum()

0

### df_3: twitter API data

In [29]:
df_3.head()

   favorite_count  retweet_count            tweet_id
0           38689           8558  892420643555336193
1           33164           6292  892177421306343426
2           24966           4174  891815181378084864
3           42074           8689  891689557279858688
4           40227           9451  891327558926688256

In [30]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2345 entries, 0 to 2344
Data columns (total 3 columns):
favorite_count    2345 non-null int64
retweet_count     2345 non-null int64
tweet_id          2345 non-null int64
dtypes: int64(3)
memory usage: 55.0 KB

In [31]:
df_3.describe()

       favorite_count  retweet_count      tweet_id
count     2345.000000    2345.000000  2.345000e+03
mean      8044.695949    3015.050746  7.422940e+17
std      12105.024041    5015.248880  6.833642e+16
min          0.000000       0.000000  6.660209e+17
25%       1402.000000     605.000000  6.783802e+17
50%       3529.000000    1404.000000  7.189392e+17
75%       9947.000000    3510.000000  7.986979e+17
max     142995.000000   77131.000000  8.924206e+17

In [32]:
df_3.favorite_count.value_counts()

0        170
1233       5
456        4
694        3
526        3
258        3
2917       3
547        3
1472       3
2601       3
1404       3
1007       3
1160       2
3160       2
334        2
4747       2
1149       2
10255      2
5771       2
3232       2
4450       2
3363       2
2303       2
2314       2
1647       2
4362       2
1596       2
654        2
752        2
2262       2
        ...
2678       1
629        1
149        1
567        1
2618       1
2620       1
573        1
27202      1
8771       1
1498       1
585        1
6732       1
4685       1
2638       1
25167      1
4689       1
14964      1
595        1
25173      1
2650       1
605        1
6752       1
609        1
29287      1
17001      1
5514       1
476        1
2670       1
8819       1
12287      1
Name: favorite_count, Length: 2025, dtype: int64

In [33]:
df_3.retweet_count.value_counts()

1301     5
373      5
1131     4
270      4
92       4
822      4
551      4
45       4
496      4
2611     4
390      4
316      4
588      4
1088     4
2880     4
528      4
131      4
807      3
93       3
3756     3
142      3
328      3
558      3
130      3
569      3
765      3
544      3
812      3
557      3
1495     3
        ..
2488     1
443      1
445      1
6590     1
4543     1
453      1
2506     1
2452     1
4489     1
2392     1
367      1
347      1
2404     1
357      1
570      1
361      1
2410     1
363      1
2412     1
2145     1
2438     1
6514     1
371      1
2420     1
375      1
383      1
39296    1
2434     1
389      1
0        1
Name: retweet_count, Length: 1718, dtype: int64

Issues:
- Order of columns is not as desired, tweet_id should be first
- favorite_count has 170 columns with value 0 which seems raises questions when followers are close to 7million and tweets are about cute dogs

### Summarizing quality and tidiness issues

#### Quality Issues

##### df_1: twitter_archive 

1. dtypes
    - tweet_id: int64
    - in_reply_to_status_id: float64
    - in_reply_to_user_id: float64
    - retweeted_status_id: float64
    - retweeted_status_user_id: float64 

2. timestamps  
    - timestamps column is a string
    - retweeted_status_timestamp is a string
        - not an issue to worry if we drop retweets

3. source is in html format and not text

4. Missing values
    - in_reply_to_status_id & in_reply_to_user_id
    - retweeted_status_id, retweeted_status_user_id & retweeted_status_timestamp 
    - will create separate dataframes for these

5. expanded_urls 
    - have multiple urls for some entries
        - can be separated into different urls
        - gofundme urls can be extracted
    - expanded_urls have whitespace for some entries
    - missing entries for urls

6. Some of the tweet texts have shortened urls included
    - these are not needed thus they can be deleted from columns

7. rating_numerator
    - rating_numerator has min value as 0 and high maximum value
        - checking value_counts reveals a good picture of range and outliers
8. rating_denominator
   - rating_denominator has min value as 0 and high maximum value
        - checking value_counts reveals less issues with denominator but we can still see some outliers

##### df_2 : image-predictions.tsv
9. non descriptive column names
10. p1, p2, p3
    - inconsistent alphabetic casing 
    - contain "_" instead of space
11. tweet_id is of int64 dtype
12. breed of dog needs to be concluded 

##### df_3: twitter API data
There are only few issues with this since it is from a semi structured source. These issues can be ignored as this dataframe will be merged eventually
   - Order of columns is not as desired, tweet_id should be first
   - favorite_count has 170 columns with value 0 which seems raises questions when followers are close to 7 million and tweets are about cute dogs 


#### Tidiness Issues

1.	attributes like doggo, pupper, floofer, puppo seem out of place
2.	unwanted columns
3.	all three datasets need to be merged
4.	column order needs to be changed
5.  separate tables for retweets and replies
    - would have already done this in earlier steps

## Cleaning

In [34]:
# create a copy for each dataframe for cleaning
df_1c=df_1.copy()
df_2c=df_2.copy()
df_3c=df_3.copy()

### Issue 1: Fixing dtypes
- tweet_id: int64

Not fixing following since they will be dropped eventually due to presence of NaN
- in_reply_to_status_id: float64
- in_reply_to_user_id: float64
- retweeted_status_id: float64
- retweeted_status_user_id: float64

#### Define
Use astype to convert them into strings

#### Code

In [35]:
df_1c['tweet_id'] = df_1c.tweet_id.astype(str)

#### Check

In [36]:
df_1c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null object
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(2), object(11)
memory usage: 313.0+ KB

In [37]:
type(df_1c.tweet_id[0])

str

### Issue 2: timestamp and retweeted_status_timestamp of type str and not timestamp

#### Define
use pd.to_datetime to comvert to a datetime64 (timestamp type for scalar value)

#### Code

In [38]:
df_1c['timestamp'] = pd.to_datetime(df_1c.timestamp)
df_1c['retweeted_status_timestamp'] = pd.to_datetime(df_1c.retweeted_status_timestamp)

#### Check

In [39]:
df_1c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null object
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null datetime64[ns]
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null datetime64[ns]
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: datetime64[ns](2), float64(4), int64(2), object(9)
memory usage: 313.0+ KB

### Issue 3: source is in html format and not text

#### Define
Use the split function and extract the source name and then replace with shortened name if needed

#### Code

In [40]:
df_1c['source']=df_1c.source.str.split('>', expand=True)[1]
df_1c['source']=df_1c.source.str.split('<', expand=True)[0]
df_1c.source.replace("Vine - Make a Scene", "Vine", inplace=True)

#### Check

In [41]:
df_1c.source.value_counts()

Twitter for iPhone    2221
Vine                    91
Twitter Web Client      33
TweetDeck               11
Name: source, dtype: int64

### Issue 4: retweets and replies columns have a lot of Nan

#### Define
drop retweets and make a separate table just in case we need it later
- use notna to create the new retweet dataframe 
- use isnull to mask and recreate the dataframe
- drop columns for retweets
- use notna to create the new replies dataframe 
- drop columns for retweets

#### Code

In [42]:
df_4 = df_1c[df_1c.retweeted_status_id.notna()]
df_5 = df_1c[df_1c.in_reply_to_status_id.notna()]
df_1c['is_reply']=df_1c.apply(lambda x: 1 if not np.isnan(x['in_reply_to_status_id']) else 0, axis=1)
df_1c = df_1c[df_1c.retweeted_status_id.isnull()]
df_1c.drop(columns=['in_reply_to_status_id', 'in_reply_to_user_id', 'retweeted_status_id', 'retweeted_status_user_id', 'retweeted_status_timestamp'], inplace=True)

#### Check

In [43]:
df_4.shape, df_1c.shape

((181, 17), (2175, 13))

In [44]:
df_4.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
19,888202515573088257,NaN,NaN,2017-07-21 01:02:36,Twitter for iPhone,RT @dog_rates: This is Canela. She attempted s...,8.874740e+17,4.196984e+09,2017-07-19 00:47:34,https://twitter.com/dog_rates/status/887473957...,13,10,Canela,None,None,None,None
32,886054160059072513,NaN,NaN,2017-07-15 02:45:48,Twitter for iPhone,RT @Athletics: 12/10 #BATP https://t.co/WxwJmv...,8.860537e+17,1.960740e+07,2017-07-15 02:44:07,https://twitter.com/dog_rates/status/886053434...,12,10,None,None,None,None,None
36,885311592912609280,NaN,NaN,2017-07-13 01:35:06,Twitter for iPhone,RT @dog_rates: This is Lilly. She just paralle...,8.305833e+17,4.196984e+09,2017-02-12 01:04:29,https://twitter.com/dog_rates/status/830583320...,13,10,Lilly,None,None,None,None
68,879130579576475649,NaN,NaN,2017-06-26 00:13:58,Twitter for iPhone,RT @dog_rates: This is Emmy. She was adopted t...,8.780576e+17,4.196984e+09,2017-06-23 01:10:23,https://twitter.com/dog_rates/status/878057613...,14,10,Emmy,None,None,None,None
73,878404777348136964,NaN,NaN,2017-06-24 00:09:53,Twitter for iPhone,RT @dog_rates: Meet Shadow. In an attempt to r...,8.782815e+17,4.196984e+09,2017-06-23 16:00:04,"https://www.gofundme.com/3yd6y1c,https://twitt...",13,10,Shadow,None,None,None,None

In [45]:
df_5.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
30,886267009285017600,8.862664e+17,2.281182e+09,2017-07-15 16:51:35,Twitter for iPhone,@NonWhiteHat @MayhewMayhem omg hello tanner yo...,NaN,NaN,NaT,NaN,12,10,None,None,None,None,None
55,881633300179243008,8.816070e+17,4.738443e+07,2017-07-02 21:58:53,Twitter for iPhone,@roushfenway These are good dogs but 17/10 is ...,NaN,NaN,NaT,NaN,17,10,None,None,None,None,None
64,879674319642796034,8.795538e+17,3.105441e+09,2017-06-27 12:14:36,Twitter for iPhone,@RealKentMurphy 14/10 confirmed,NaN,NaN,NaT,NaN,14,10,None,None,None,None,None
113,870726314365509632,8.707262e+17,1.648776e+07,2017-06-02 19:38:25,Twitter for iPhone,@ComplicitOwl @ShopWeRateDogs &gt;10/10 is res...,NaN,NaN,NaT,NaN,10,10,None,None,None,None,None
148,863427515083354112,8.634256e+17,7.759620e+07,2017-05-13 16:15:35,Twitter for iPhone,@Jack_Septic_Eye I'd need a few more pics to p...,NaN,NaN,NaT,NaN,12,10,None,None,None,None,None

In [46]:
df_1c.head()

,tweet_id,timestamp,source,text,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,is_reply
0,892420643555336193,2017-08-01 16:23:56,Twitter for iPhone,This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None,0
1,892177421306343426,2017-08-01 00:17:27,Twitter for iPhone,This is Tilly. She's just checking pup on you....,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None,0
2,891815181378084864,2017-07-31 00:18:03,Twitter for iPhone,This is Archie. He is a rare Norwegian Pouncin...,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None,0
3,891689557279858688,2017-07-30 15:58:51,Twitter for iPhone,This is Darla. She commenced a snooze mid meal...,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None,0
4,891327558926688256,2017-07-29 16:00:24,Twitter for iPhone,This is Franklin. He would like you to stop ca...,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None,0

In [47]:
df_1c.isnull().sum()

tweet_id               0
timestamp              0
source                 0
text                   0
expanded_urls         58
rating_numerator       0
rating_denominator     0
name                   0
doggo                  0
floofer                0
pupper                 0
puppo                  0
is_reply               0
dtype: int64

### Issue 5: expanded_urls have whitespaces and multiple urls for some entries, some values are NaN

#### Define 
- create a new column for url using tweet_id
- drop expanded urls

#### Code

In [48]:
df_1c['url']='https://twitter.com/dog_rates/status/' + df_1c['tweet_id']
df_1c.drop('expanded_urls', axis=1,inplace=True)

#### Check

In [49]:
df_1c.url.isnull().sum(), df_1c.url

(0, 0       https://twitter.com/dog_rates/status/892420643...
 1       https://twitter.com/dog_rates/status/892177421...
 2       https://twitter.com/dog_rates/status/891815181...
 3       https://twitter.com/dog_rates/status/891689557...
 4       https://twitter.com/dog_rates/status/891327558...
 5       https://twitter.com/dog_rates/status/891087950...
 6       https://twitter.com/dog_rates/status/890971913...
 7       https://twitter.com/dog_rates/status/890729181...
 8       https://twitter.com/dog_rates/status/890609185...
 9       https://twitter.com/dog_rates/status/890240255...
 10      https://twitter.com/dog_rates/status/890006608...
 11      https://twitter.com/dog_rates/status/889880896...
 12      https://twitter.com/dog_rates/status/889665388...
 13      https://twitter.com/dog_rates/status/889638837...
 14      https://twitter.com/dog_rates/status/889531135...
 15      https://twitter.com/dog_rates/status/889278841...
 16      https://twitter.com/dog_rates/status/888917238...
 17      https://twitter.com/dog_rates/status/888804989...
 18      https://twitter.com/dog_rates/status/888554962...
 20      https://twitter.com/dog_rates/status/888078434...
 21      https://twitter.com/dog_rates/status/887705289...
 22      https://twitter.com/dog_rates/status/887517139...
 23      https://twitter.com/dog_rates/status/887473957...
 24      https://twitter.com/dog_rates/status/887343217...
 25      https://twitter.com/dog_rates/status/887101392...
 26      https://twitter.com/dog_rates/status/886983233...
 27      https://twitter.com/dog_rates/status/886736880...
 28      https://twitter.com/dog_rates/status/886680336...
 29      https://twitter.com/dog_rates/status/886366144...
 30      https://twitter.com/dog_rates/status/886267009...
                               ...
 2326    https://twitter.com/dog_rates/status/666411507...
 2327    https://twitter.com/dog_rates/status/666407126...
 2328    https://twitter.com/dog_rates/status/666396247...
 2329    https://twitter.com/dog_rates/status/666373753...
 2330    https://twitter.com/dog_rates/status/666362758...
 2331    https://twitter.com/dog_rates/status/666353288...
 2332    https://twitter.com/dog_rates/status/666345417...
 2333    https://twitter.com/dog_rates/status/666337882...
 2334    https://twitter.com/dog_rates/status/666293911...
 2335    https://twitter.com/dog_rates/status/666287406...
 2336    https://twitter.com/dog_rates/status/666273097...
 2337    https://twitter.com/dog_rates/status/666268910...
 2338    https://twitter.com/dog_rates/status/666104133...
 2339    https://twitter.com/dog_rates/status/666102155...
 2340    https://twitter.com/dog_rates/status/666099513...
 2341    https://twitter.com/dog_rates/status/666094000...
 2342    https://twitter.com/dog_rates/status/666082916...
 2343    https://twitter.com/dog_rates/status/666073100...
 2344    https://twitter.com/dog_rates/status/666071193...
 2345    https://twitter.com/dog_rates/status/666063827...
 2346    https://twitter.com/dog_rates/status/666058600...
 2347    https://twitter.com/dog_rates/status/666057090...
 2348    https://twitter.com/dog_rates/status/666055525...
 2349    https://twitter.com/dog_rates/status/666051853...
 2350    https://twitter.com/dog_rates/status/666050758...
 2351    https://twitter.com/dog_rates/status/666049248...
 2352    https://twitter.com/dog_rates/status/666044226...
 2353    https://twitter.com/dog_rates/status/666033412...
 2354    https://twitter.com/dog_rates/status/666029285...
 2355    https://twitter.com/dog_rates/status/666020888...
 Name: url, Length: 2175, dtype: object)

In [50]:
df_1c.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2355
Data columns (total 13 columns):
tweet_id              2175 non-null object
timestamp             2175 non-null datetime64[ns]
source                2175 non-null object
text                  2175 non-null object
rating_numerator      2175 non-null int64
rating_denominator    2175 non-null int64
name                  2175 non-null object
doggo                 2175 non-null object
floofer               2175 non-null object
pupper                2175 non-null object
puppo                 2175 non-null object
is_reply              2175 non-null int64
url                   2175 non-null object
dtypes: datetime64[ns](1), int64(3), object(9)
memory usage: 237.9+ KB

### Issue 6: Some of the tweet texts have shortened urls included

#### Define
use replace and strip to get the desired result

#### Code

In [51]:
df_1c['text'] = df_1c.text.str.replace('https://.*', "", ).str.strip()

#### Check

In [52]:
df_1c.text.str.contains('https').sum()

0

In [53]:
df_1c.text[15]

"This is Oliver. You're witnessing one of his many brutal attacks. Seems to be playing with his victim. 13/10 fr*ckin frightening #BarkWeek"

### Issue 7&8: rating numerator and denominator have invalid ratings and unimportant outliers

#### Define
on post https://twitter.com/dog_rates/status/838085839343206401 WeRateDogs says they are looking for first 15/10 so we know that no rates are above 14, except for a few like Snoop Dogg or Satan's dog which have recieved 420/10 or 666/10. 

Since these are all outliers we can drop them

Some others are high numerators with high denominators, usually   litter of puppers or pack of doggos, these can be figured out by looking at denominator which we saw earlier didn't have too many outliers

- check all with denomiator neither 10 nor divisible by 10
    - note for change or drop 
- create a divisor column that will divide numerator and denominator for litters and packs
- check outliers and drop them

In [54]:
df_1d=df_1c.copy()

In [55]:
df_1c['rate']=df_1c.text.str.extract("(\d+\.?\d*/\d+)", expand=True)

In [56]:
df_1c['rate'].isnull().sum()

0

In [57]:
rate = df_1c['rate'].str.split('/')
df_1c['rating_numerator']= df_1c['rate'].str.split('/', expand=True)[0].astype(float)
df_1c['rating_denominator'] = df_1c['rate'].str.split('/', expand=True)[1].astype(float)
df_1c.drop('rate', axis=1)

,tweet_id,timestamp,source,text,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,is_reply,url
0,892420643555336193,2017-08-01 16:23:56,Twitter for iPhone,This is Phineas. He's a mystical boy. Only eve...,13.0,10.0,Phineas,None,None,None,None,0,https://twitter.com/dog_rates/status/892420643...
1,892177421306343426,2017-08-01 00:17:27,Twitter for iPhone,This is Tilly. She's just checking pup on you....,13.0,10.0,Tilly,None,None,None,None,0,https://twitter.com/dog_rates/status/892177421...
2,891815181378084864,2017-07-31 00:18:03,Twitter for iPhone,This is Archie. He is a rare Norwegian Pouncin...,12.0,10.0,Archie,None,None,None,None,0,https://twitter.com/dog_rates/status/891815181...
3,891689557279858688,2017-07-30 15:58:51,Twitter for iPhone,This is Darla. She commenced a snooze mid meal...,13.0,10.0,Darla,None,None,None,None,0,https://twitter.com/dog_rates/status/891689557...
4,891327558926688256,2017-07-29 16:00:24,Twitter for iPhone,This is Franklin. He would like you to stop ca...,12.0,10.0,Franklin,None,None,None,None,0,https://twitter.com/dog_rates/status/891327558...
5,891087950875897856,2017-07-29 00:08:17,Twitter for iPhone,Here we have a majestic great white breaching ...,13.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/891087950...
6,890971913173991426,2017-07-28 16:27:12,Twitter for iPhone,Meet Jax. He enjoys ice cream so much he gets ...,13.0,10.0,Jax,None,None,None,None,0,https://twitter.com/dog_rates/status/890971913...
7,890729181411237888,2017-07-28 00:22:40,Twitter for iPhone,When you watch your owner call another dog a g...,13.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/890729181...
8,890609185150312448,2017-07-27 16:25:51,Twitter for iPhone,This is Zoey. She doesn't want to be one of th...,13.0,10.0,Zoey,None,None,None,None,0,https://twitter.com/dog_rates/status/890609185...
9,890240255349198849,2017-07-26 15:59:51,Twitter for iPhone,This is Cassie. She is a college pup. Studying...,14.0,10.0,Cassie,doggo,None,None,None,0,https://twitter.com/dog_rates/status/890240255...
10,890006608113172480,2017-07-26 00:31:25,Twitter for iPhone,This is Koda. He is a South Australian decksha...,13.0,10.0,Koda,None,None,None,None,0,https://twitter.com/dog_rates/status/890006608...
11,889880896479866881,2017-07-25 16:11:53,Twitter for iPhone,This is Bruno. He is a service shark. Only get...,13.0,10.0,Bruno,None,None,None,None,0,https://twitter.com/dog_rates/status/889880896...
12,889665388333682689,2017-07-25 01:55:32,Twitter for iPhone,Here's a puppo that seems to be on the fence a...,13.0,10.0,None,None,None,None,puppo,0,https://twitter.com/dog_rates/status/889665388...
13,889638837579907072,2017-07-25 00:10:02,Twitter for iPhone,This is Ted. He does his best. Sometimes that'...,12.0,10.0,Ted,None,None,None,None,0,https://twitter.com/dog_rates/status/889638837...
14,889531135344209921,2017-07-24 17:02:04,Twitter for iPhone,This is Stuart. He's sporting his favorite fan...,13.0,10.0,Stuart,None,None,None,puppo,0,https://twitter.com/dog_rates/status/889531135...
15,889278841981685760,2017-07-24 00:19:32,Twitter for iPhone,This is Oliver. You're witnessing one of his m...,13.0,10.0,Oliver,None,None,None,None,0,https://twitter.com/dog_rates/status/889278841...
16,888917238123831296,2017-07-23 00:22:39,Twitter for iPhone,This is Jim. He found a fren. Taught him how t...,12.0,10.0,Jim,None,None,None,None,0,https://twitter.com/dog_rates/status/888917238...
17,888804989199671297,2017-07-22 16:56:37,Twitter for iPhone,This is Zeke. He has a new stick. Very proud o...,13.0,10.0,Zeke,None,None,None,None,0,https://twitter.com/dog_rates/status/888804989...
18,888554962724278272,2017-07-22 00:23:06,Twitter for iPhone,This is Ralphus. He's powering up. Attempting ...,13.0,10.0,Ralphus,None,None,None,None,0,https://twitter.com/dog_rates/status/888554962...
20,888078434458587136,2017-07-20 16:49:33,Twitter for iPhone,This is Gerald. He was just told he didn't get...,12.0,10.0,Gerald,None,None,None,None,0,https://twitter.com/dog_rates/status/888078434...
21,887705289381826560,2017-07-19 16:06:48,Twitter for iPhone,This is Jeffrey. He has a monopoly on the pool...,13.0,10.0,Jeffrey,None,None,None,None,0,https://twitter.com/dog_rates/status/887705289...
22,887517139158093824,2017-07-19 03:39:09,Twitter for iPhone,I've yet to rate a Venezuelan Hover Wiener. Th...,14.0,10.0,such,None,None,None,None,0,https://twitter.com/dog_rates/status/887517139...
23,887473957103951883,2017-07-19 00:47:34,Twitter for iPhone,This is Canela. She attempted some fancy porch...,13.0,10.0,Canela,None,None,None,None,0,https://twitter.com/dog_rates/status/887473957...
24,887343217045368832,2017-07-18 16:08:03,Twitter for iPhone,You may not have known you needed to see this ...,13.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/887343217...
25,887101392804085760,2017-07-18 00:07:08,Twitter for iPhone,This... is a Jubilant Antarctic House Bear. We...,12.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/887101392...
26,886983233522544640,2017-07-17 16:17:36,Twitter for iPhone,This is Maya. She's very shy. Rarely leaves he...,13.0,10.0,Maya,None,None,None,None,0,https://twitter.com/dog_rates/status/886983233...
27,886736880519319552,2017-07-16 23:58:41,Twitter for iPhone,This is Mingus. He's a wonderful father to his...,13.0,10.0,Mingus,None,None,None,None,0,https://twitter.com/dog_rates/status/886736880...
28,886680336477933568,2017-07-16 20:14:00,Twitter for iPhone,This is Derek. He's late for a dog meeting. 13...,13.0,10.0,Derek,None,None,None,None,0,https://twitter.com/dog_rates/status/886680336...
29,886366144734445568,2017-07-15 23:25:31,Twitter for iPhone,This is Roscoe. Another pupper fallen victim t...,12.0,10.0,Roscoe,None,None,pupper,None,0,https://twitter.com/dog_rates/status/886366144...
30,886267009285017600,2017-07-15 16:51:35,Twitter for iPhone,@NonWhiteHat @MayhewMayhem omg hello tanner yo...,12.0,10.0,None,None,None,None,None,1,https://twitter.com/dog_rates/status/886267009...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326,666411507551481857,2015-11-17 00:24:19,Twitter for iPhone,This is quite the dog. Gets really excited whe...,2.0,10.0,quite,None,None,None,None,0,https://twitter.com/dog_rates/status/666411507...
2327,666407126856765440,2015-11-17 00:06:54,Twitter for iPhone,This is a southern Vesuvius bumblegruff. Can d...,7.0,10.0,a,None,None,None,None,0,https://twitter.com/dog_rates/status/666407126...
2328,666396247373291520,2015-11-16 23:23:41,Twitter for iPhone,Oh goodness. A super rare northeast Qdoba kang...,9.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666396247...
2329,666373753744588802,2015-11-16 21:54:18,Twitter for iPhone,Those are sunglasses and a jean jacket. 11/10 ...,11.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666373753...
2330,666362758909284353,2015-11-16 21:10:36,Twitter for iPhone,Unique dog here. Very small. Lives in containe...,6.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666362758...
2331,666353288456101888,2015-11-16 20:32:58,Twitter for iPhone,Here we have a mixed Asiago from the Galápagos...,8.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666353288...
2332,666345417576210432,2015-11-16 20:01:42,Twitter for iPhone,Look at this jokester thinking seat belt laws ...,10.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666345417...
2333,666337882303524864,2015-11-16 19:31:45,Twitter for iPhone,This is an extremely rare horned Parthenon. No...,9.0,10.0,an,None,None,None,None,0,https://twitter.com/dog_rates/status/666337882...
2334,666293911632134144,2015-11-16 16:37:02,Twitter for iPhone,This is a funny dog. Weird toes. Won't come do...,3.0,10.0,a,None,None,None,None,0,https://twitter.com/dog_rates/status/666293911...
2335,666287406224695296,2015-11-16 16:11:11,Twitter for iPhone,This is an Albanian 3 1/2 legged Episcopalian...,1.0,2.0,an,None,None,None,None,0,https://twitter.com/dog_rates/status/666287406...
2336,666273097616637952,2015-11-16 15:14:19,Twitter for iPhone,Can take selfies 11/10,11.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666273097...
2337,666268910803644416,2015-11-16 14:57:41,Twitter for iPhone,Very concerned about fellow dog trapped in com...,10.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666268910...
2338,666104133288665088,2015-11-16 04:02:55,Twitter for iPhone,Not familiar with this breed. No tail (weird)....,1.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666104133...
2339,666102155909144576,2015-11-16 03:55:04,Twitter for iPhone,Oh my. Here you are seeing an Adobe Setter giv...,11.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666102155...
2340,666099513787052032,2015-11-16 03:44:34,Twitter for iPhone,Can stand on stump for what seems like a while...,8.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666099513...
2341,666094000022159362,2015-11-16 03:22:39,Twitter for iPhone,This appears to be a Mongolian Presbyterian mi...,9.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666094000...
2342,666082916733198337,2015-11-16 02:38:37,Twitter for iPhone,Here we have a well-established sunblockerspan...,6.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666082916...
2343,666073100786774016,2015-11-16 01:59:36,Twitter for iPhone,Let's hope this flight isn't Malaysian (lol). ...,10.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666073100...
2344,666071193221509120,2015-11-16 01:52:02,Twitter for iPhone,Here we have a northern speckled Rhododendron....,9.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666071193...
2345,666063827256086533,2015-11-16 01:22:45,Twitter for iPhone,This is the happiest dog you will ever see. Ve...,10.0,10.0,the,None,None,None,None,0,https://twitter.com/dog_rates/status/666063827...
2346,666058600524156928,2015-11-16 01:01:59,Twitter for iPhone,Here is the Rand Paul of retrievers folks! He'...,8.0,10.0,the,None,None,None,None,0,https://twitter.com/dog_rates/status/666058600...
2347,666057090499244032,2015-11-16 00:55:59,Twitter for iPhone,My oh my. This is a rare blond Canadian terrie...,9.0,10.0,a,None,None,None,None,0,https://twitter.com/dog_rates/status/666057090...
2348,666055525042405380,2015-11-16 00:49:46,Twitter for iPhone,Here is a Siberian heavily armored polar bear ...,10.0,10.0,a,None,None,None,None,0,https://twitter.com/dog_rates/status/666055525...
2349,666051853826850816,2015-11-16 00:35:11,Twitter for iPhone,This is an odd dog. Hard on the outside but lo...,2.0,10.0,an,None,None,None,None,0,https://twitter.com/dog_rates/status/666051853...
2350,666050758794694657,2015-11-16 00:30:50,Twitter for iPhone,This is a truly beautiful English Wilson Staff...,10.0,10.0,a,None,None,None,None,0,https://twitter.com/dog_rates/status/666050758...
2351,666049248165822465,2015-11-16 00:24:50,Twitter for iPhone,Here we have a 1949 1st generation vulpix. Enj...,5.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666049248...
2352,666044226329800704,2015-11-16 00:04:52,Twitter for iPhone,This is a purebred Piers Morgan. Loves to Netf...,6.0,10.0,a,None,None,None,None,0,https://twitter.com/dog_rates/status/666044226...
2353,666033412701032449,2015-11-15 23:21:54,Twitter for iPhone,Here is a very happy pup. Big fan of well-main...,9.0,10.0,a,None,None,None,None,0,https://twitter.com/dog_rates/status/666033412...
2354,666029285002620928,2015-11-15 23:05:30,Twitter for iPhone,This is a western brown Mitsubishi terrier. Up...,7.0,10.0,a,None,None,None,None,0,https://twitter.com/dog_rates/status/666029285...
2355,666020888022790149,2015-11-15 22:32:08,Twitter for iPhone,Here we have a Japanese Irish Setter. Lost eye...,8.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/666020888...

#### Reassess

In [58]:
df_1c[(df_1c.rating_numerator>100)]

,tweet_id,timestamp,source,text,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,is_reply,url,rate
188,855862651834028034,2017-04-22 19:15:32,Twitter for iPhone,@dhmontgomery We also gave snoop dogg a 420/10...,420.0,10.0,None,None,None,None,None,1,https://twitter.com/dog_rates/status/855862651...,420/10
189,855860136149123072,2017-04-22 19:05:32,Twitter for iPhone,@s8n You tried very hard to portray this good ...,666.0,10.0,None,None,None,None,None,1,https://twitter.com/dog_rates/status/855860136...,666/10
290,838150277551247360,2017-03-04 22:12:52,Twitter for iPhone,@markhoppus 182/10,182.0,10.0,None,None,None,None,None,1,https://twitter.com/dog_rates/status/838150277...,182/10
313,835246439529840640,2017-02-24 21:54:03,Twitter for iPhone,@jonnysun @Lin_Manuel ok jomny I know you're e...,960.0,0.0,None,None,None,None,None,1,https://twitter.com/dog_rates/status/835246439...,960/00
902,758467244762497024,2016-07-28 01:00:57,Twitter for iPhone,Why does this never happen at my front door......,165.0,150.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/758467244...,165/150
979,749981277374128128,2016-07-04 15:00:45,TweetDeck,This is Atticus. He's quite simply America af....,1776.0,10.0,Atticus,None,None,None,None,0,https://twitter.com/dog_rates/status/749981277...,1776/10
1120,731156023742988288,2016-05-13 16:15:54,Twitter for iPhone,Say hello to this unbelievably well behaved sq...,204.0,170.0,this,None,None,None,None,0,https://twitter.com/dog_rates/status/731156023...,204/170
1634,684225744407494656,2016-01-05 04:11:44,Twitter for iPhone,"Two sneaky puppers were not initially seen, mo...",143.0,130.0,None,None,None,None,None,1,https://twitter.com/dog_rates/status/684225744...,143/130
1635,684222868335505415,2016-01-05 04:00:18,Twitter for iPhone,Someone help the girl is being mugged. Several...,121.0,110.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/684222868...,121/110
1779,677716515794329600,2015-12-18 05:06:23,Twitter for iPhone,IT'S PUPPERGEDDON. Total of 144/120 ...I think,144.0,120.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/677716515...,144/120
2074,670842764863651840,2015-11-29 05:52:33,Twitter for iPhone,After so many requests... here you go.\n\nGood...,420.0,10.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/670842764...,420/10

In [59]:
df_1c[((df_1c.rating_denominator%10)!=0)]

,tweet_id,timestamp,source,text,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,is_reply,url,rate
342,832088576586297345,2017-02-16 04:45:50,Twitter for iPhone,@docmisterio account started on 11/15/15,11.0,15.0,None,None,None,None,None,1,https://twitter.com/dog_rates/status/832088576...,11/15
516,810984652412424192,2016-12-19 23:06:23,Twitter for iPhone,Meet Sam. She smiles 24/7 &amp; secretly aspir...,24.0,7.0,Sam,None,None,None,None,0,https://twitter.com/dog_rates/status/810984652...,24/7
1068,740373189193256964,2016-06-08 02:41:38,Twitter for iPhone,"After so many requests, this is Bretagne. She ...",9.0,11.0,None,None,None,None,None,0,https://twitter.com/dog_rates/status/740373189...,9/11
1662,682962037429899265,2016-01-01 16:30:13,Twitter for iPhone,This is Darrel. He just robbed a 7/11 and is i...,7.0,11.0,Darrel,None,None,None,None,0,https://twitter.com/dog_rates/status/682962037...,7/11
1663,682808988178739200,2016-01-01 06:22:03,Twitter for iPhone,"I'm aware that I could've said 20/16, but here...",20.0,16.0,None,None,None,None,None,1,https://twitter.com/dog_rates/status/682808988...,20/16
2335,666287406224695296,2015-11-16 16:11:11,Twitter for iPhone,This is an Albanian 3 1/2 legged Episcopalian...,1.0,2.0,an,None,None,None,None,0,https://twitter.com/dog_rates/status/666287406...,1/2

- We can drop all tweets that have rating numerator above 100 and denominator as 10
- We can also drop tweets that have denominator not equal 10 or divisible by 10 
- Some entries seem to have an error which we will fix before dropping, they are documented below
    - 740373189193256964 Bretagne 14/10 (actually post says this is second such dog to get this, its last of 9/11 rescue dogs)
    - 682962037429899265 Darrel 10/10
    - 666287406224695296 Episcopalian 9/10

#### Code

In [60]:
A= {'740373189193256964': ['Bretagne', 14],
    '682962037429899265': ['Darrel',  10],
    '666287406224695296': ['Episcopalian', 9],
    '881633300179243008': [None, 13]}

In [61]:
for key,value in A.items():
    (df_1c.loc[df_1c['tweet_id'] == key, 'name' ])=value[0]
for key,value in A.items():
    (df_1c.loc[df_1c['tweet_id'] == key, 'rating_numerator' ])=value[1]
for key,value in A.items():
    (df_1c.loc[df_1c['tweet_id'] == key, 'rating_denominator' ])=10

In [62]:
drop_list=(df_1c[(df_1c.rating_numerator>100)& (df_1c.rating_denominator==10)].tweet_id).tolist()
drop_list2 = df_1c[((df_1c.rating_denominator%10)!=0)].tweet_id.tolist()
drop_list.extend(drop_list2)

In [63]:
drop_list

['855862651834028034',
 '855860136149123072',
 '838150277551247360',
 '749981277374128128',
 '670842764863651840',
 '832088576586297345',
 '810984652412424192',
 '682808988178739200']

In [64]:
for dropper in drop_list:
    df_1c.drop(df_1c[df_1c['tweet_id'] == dropper].index, inplace=True)

In [65]:
df_1c['divider'] = df_1d.rating_denominator/10

In [66]:
df_1c['rating_denominator']= df_1c['rating_denominator']/df_1c['divider']
df_1c['rating_numerator']= df_1c['rating_numerator']/df_1c['divider']
df_1c.drop('divider',axis=1, inplace=True)

In [67]:
df_1c.drop(df_1c.loc[(df_1c['rating_denominator']!=10)|(df_1c.rating_numerator<4)].index, inplace=True)

#### Check

In [68]:
df_1c.rating_numerator.value_counts()

12.00    504
10.00    444
11.00    431
13.00    308
9.00     156
8.00      98
7.00      53
14.00     43
5.00      34
6.00      32
4.00      15
11.27      1
15.00      1
9.50       1
13.50      1
11.26      1
9.75       1
Name: rating_numerator, dtype: int64

In [69]:
df_1d.rating_numerator.value_counts()

12      500
10      442
11      426
13      307
9       156
8        98
7        54
14       43
5        36
6        32
3        19
4        17
2         9
1         8
420       2
0         2
20        1
24        1
26        1
84        1
44        1
50        1
60        1
80        1
165       1
88        1
144       1
182       1
143       1
666       1
960       1
1776      1
15        1
17        1
27        1
45        1
75        1
99        1
121       1
204       1
Name: rating_numerator, dtype: int64

In [70]:
df_1c.rating_denominator.value_counts(),

(10.0    2124
 Name: rating_denominator, dtype: int64,)

In [71]:
df_1c.shape

(2124, 14)

We can now drop the rating denominator column since all values are equal to 10

In [72]:
df_1c.drop('rating_denominator', axis=1, inplace=True)

### df_2 : image-predictions.tsv

In [73]:
df_2c.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

### Issue 9: renaming non descriptive columns

#### Define
Use pandas rename function to rename the columns

In [74]:
df_2c.rename(columns={'p1': 'p1_most_probable_breed',
              'p1_conf': 'p1_confidence',
              'p1_dog': 'p1_is_dog_breed',
              'p2': 'p2_most_probable_breed',
              'p2_conf': 'p2_confidence',
              'p2_dog': 'p2_is_dog_breed',
              'p3': 'p3_most_probable_breed',
              'p3_conf': 'p3_confidence',
              'p3_dog': 'p3_is_dog_breed'}, inplace=True)

#### Check

In [75]:
df_2c.head()

,tweet_id,jpg_url,img_num,p1_most_probable_breed,p1_confidence,p1_is_dog_breed,p2_most_probable_breed,p2_confidence,p2_is_dog_breed,p3_most_probable_breed,p3_confidence,p3_is_dog_breed
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

### Issue 10: p1, p2, p3 have inconsistent casing and "_" instead of spaces

#### Define
use str.lower() and str.replace function to change into the desired result

#### Code

In [76]:
for col_name in ['p1_most_probable_breed', 'p2_most_probable_breed', 'p3_most_probable_breed']:
    df_2c[col_name] = df_2c[col_name].str.replace('_', ' ')
    df_2c[col_name] = df_2c[col_name].str.title()

#### Check

In [77]:
df_2c.head()

,tweet_id,jpg_url,img_num,p1_most_probable_breed,p1_confidence,p1_is_dog_breed,p2_most_probable_breed,p2_confidence,p2_is_dog_breed,p3_most_probable_breed,p3_confidence,p3_is_dog_breed
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh Springer Spaniel,0.465074,True,Collie,0.156665,True,Shetland Sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,Redbone,0.506826,True,Miniature Pinscher,0.074192,True,Rhodesian Ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German Shepherd,0.596461,True,Malinois,0.138584,True,Bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian Ridgeback,0.408143,True,Redbone,0.360687,True,Miniature Pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,Miniature Pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

### Issue 11: tweet_id is of int64 dtype

#### Define
use astype to change into str

#### Code

In [78]:
df_2c.tweet_id = df_2c.tweet_id.astype(str)

#### Check

In [79]:
type(df_2c.tweet_id[0])

str

In [80]:
df_2c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id                  2075 non-null object
jpg_url                   2075 non-null object
img_num                   2075 non-null int64
p1_most_probable_breed    2075 non-null object
p1_confidence             2075 non-null float64
p1_is_dog_breed           2075 non-null bool
p2_most_probable_breed    2075 non-null object
p2_confidence             2075 non-null float64
p2_is_dog_breed           2075 non-null bool
p3_most_probable_breed    2075 non-null object
p3_confidence             2075 non-null float64
p3_is_dog_breed           2075 non-null bool
dtypes: bool(3), float64(3), int64(1), object(5)
memory usage: 152.1+ KB

### Issue 12: breed of dog needs to be concluded

#### Define
create a new column breed_fin using apply and a defined function

#### Code

In [81]:
def breed_define(row):
    if row['p1_is_dog_breed']:
        return (row['p1_most_probable_breed'])
    if row['p2_is_dog_breed']:
        return (row['p2_most_probable_breed'])
    if row['p3_is_dog_breed']:
        return (row['p3_most_probable_breed'])
    else:
        return np.nan

df_2c["breed_fin"]= df_2c.apply(breed_define, axis=1 )

#### Check

In [82]:
df_2c.isnull().sum()

tweet_id                    0
jpg_url                     0
img_num                     0
p1_most_probable_breed      0
p1_confidence               0
p1_is_dog_breed             0
p2_most_probable_breed      0
p2_confidence               0
p2_is_dog_breed             0
p3_most_probable_breed      0
p3_confidence               0
p3_is_dog_breed             0
breed_fin                 324
dtype: int64

## Tidying

### Issue 1: doggo, puppo, pupper, floofer

#### Define
Create one column for stage and another for floofer (like a dummy column with 1 and 0). Interestingly only 10 were specified as floofer

#### Code

In [83]:
for col_name in ['pupper', 'puppo', 'doggo']:
    df_1c.loc[df_1c[col_name] == col_name, 'stage'] = col_name

df_1c.loc[df_1c.floofer == 'floofer', 'floofer'] = 1
df_1c.loc[df_1c.floofer != 1, 'floofer'] = 0

In [84]:
df_1c.stage.value_counts(), df_1c.floofer.value_counts()

(pupper    223
 doggo      87
 puppo      24
 Name: stage, dtype: int64, 0    2114
 1      10
 Name: floofer, dtype: int64)

In [85]:
df_1c.head()

,tweet_id,timestamp,source,text,rating_numerator,name,doggo,floofer,pupper,puppo,is_reply,url,rate,stage
0,892420643555336193,2017-08-01 16:23:56,Twitter for iPhone,This is Phineas. He's a mystical boy. Only eve...,13.0,Phineas,None,0,None,None,0,https://twitter.com/dog_rates/status/892420643...,13/10,NaN
1,892177421306343426,2017-08-01 00:17:27,Twitter for iPhone,This is Tilly. She's just checking pup on you....,13.0,Tilly,None,0,None,None,0,https://twitter.com/dog_rates/status/892177421...,13/10,NaN
2,891815181378084864,2017-07-31 00:18:03,Twitter for iPhone,This is Archie. He is a rare Norwegian Pouncin...,12.0,Archie,None,0,None,None,0,https://twitter.com/dog_rates/status/891815181...,12/10,NaN
3,891689557279858688,2017-07-30 15:58:51,Twitter for iPhone,This is Darla. She commenced a snooze mid meal...,13.0,Darla,None,0,None,None,0,https://twitter.com/dog_rates/status/891689557...,13/10,NaN
4,891327558926688256,2017-07-29 16:00:24,Twitter for iPhone,This is Franklin. He would like you to stop ca...,12.0,Franklin,None,0,None,None,0,https://twitter.com/dog_rates/status/891327558...,12/10,NaN

### Issue 2: Drop the unwanted columns

#### Define

#### Code

In [86]:
df_1c.drop(columns=['doggo', 'pupper', 'puppo', 'rate'], inplace=True)

#### Check

In [87]:
df_1c.head()

,tweet_id,timestamp,source,text,rating_numerator,name,floofer,is_reply,url,stage
0,892420643555336193,2017-08-01 16:23:56,Twitter for iPhone,This is Phineas. He's a mystical boy. Only eve...,13.0,Phineas,0,0,https://twitter.com/dog_rates/status/892420643...,NaN
1,892177421306343426,2017-08-01 00:17:27,Twitter for iPhone,This is Tilly. She's just checking pup on you....,13.0,Tilly,0,0,https://twitter.com/dog_rates/status/892177421...,NaN
2,891815181378084864,2017-07-31 00:18:03,Twitter for iPhone,This is Archie. He is a rare Norwegian Pouncin...,12.0,Archie,0,0,https://twitter.com/dog_rates/status/891815181...,NaN
3,891689557279858688,2017-07-30 15:58:51,Twitter for iPhone,This is Darla. She commenced a snooze mid meal...,13.0,Darla,0,0,https://twitter.com/dog_rates/status/891689557...,NaN
4,891327558926688256,2017-07-29 16:00:24,Twitter for iPhone,This is Franklin. He would like you to stop ca...,12.0,Franklin,0,0,https://twitter.com/dog_rates/status/891327558...,NaN

### Issue 3: Merge all tables as needed

#### Define
use left merge

#### Code

In [88]:
df=df_1c.merge(df_2c[['tweet_id', 'jpg_url', 'breed_fin' ]], how='left', on= "tweet_id")

#### Check

In [89]:
df

,tweet_id,timestamp,source,text,rating_numerator,name,floofer,is_reply,url,stage,jpg_url,breed_fin
0,892420643555336193,2017-08-01 16:23:56,Twitter for iPhone,This is Phineas. He's a mystical boy. Only eve...,13.0,Phineas,0,0,https://twitter.com/dog_rates/status/892420643...,NaN,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,NaN
1,892177421306343426,2017-08-01 00:17:27,Twitter for iPhone,This is Tilly. She's just checking pup on you....,13.0,Tilly,0,0,https://twitter.com/dog_rates/status/892177421...,NaN,https://pbs.twimg.com/media/DGGmoV4XsAAUL6n.jpg,Chihuahua
2,891815181378084864,2017-07-31 00:18:03,Twitter for iPhone,This is Archie. He is a rare Norwegian Pouncin...,12.0,Archie,0,0,https://twitter.com/dog_rates/status/891815181...,NaN,https://pbs.twimg.com/media/DGBdLU1WsAANxJ9.jpg,Chihuahua
3,891689557279858688,2017-07-30 15:58:51,Twitter for iPhone,This is Darla. She commenced a snooze mid meal...,13.0,Darla,0,0,https://twitter.com/dog_rates/status/891689557...,NaN,https://pbs.twimg.com/media/DF_q7IAWsAEuuN8.jpg,Labrador Retriever
4,891327558926688256,2017-07-29 16:00:24,Twitter for iPhone,This is Franklin. He would like you to stop ca...,12.0,Franklin,0,0,https://twitter.com/dog_rates/status/891327558...,NaN,https://pbs.twimg.com/media/DF6hr6BUMAAzZgT.jpg,Basset
5,891087950875897856,2017-07-29 00:08:17,Twitter for iPhone,Here we have a majestic great white breaching ...,13.0,None,0,0,https://twitter.com/dog_rates/status/891087950...,NaN,https://pbs.twimg.com/media/DF3HwyEWsAABqE6.jpg,Chesapeake Bay Retriever
6,890971913173991426,2017-07-28 16:27:12,Twitter for iPhone,Meet Jax. He enjoys ice cream so much he gets ...,13.0,Jax,0,0,https://twitter.com/dog_rates/status/890971913...,NaN,https://pbs.twimg.com/media/DF1eOmZXUAALUcq.jpg,Appenzeller
7,890729181411237888,2017-07-28 00:22:40,Twitter for iPhone,When you watch your owner call another dog a g...,13.0,None,0,0,https://twitter.com/dog_rates/status/890729181...,NaN,https://pbs.twimg.com/media/DFyBahAVwAAhUTd.jpg,Pomeranian
8,890609185150312448,2017-07-27 16:25:51,Twitter for iPhone,This is Zoey. She doesn't want to be one of th...,13.0,Zoey,0,0,https://twitter.com/dog_rates/status/890609185...,NaN,https://pbs.twimg.com/media/DFwUU__XcAEpyXI.jpg,Irish Terrier
9,890240255349198849,2017-07-26 15:59:51,Twitter for iPhone,This is Cassie. She is a college pup. Studying...,14.0,Cassie,0,0,https://twitter.com/dog_rates/status/890240255...,doggo,https://pbs.twimg.com/media/DFrEyVuW0AAO3t9.jpg,Pembroke
10,890006608113172480,2017-07-26 00:31:25,Twitter for iPhone,This is Koda. He is a South Australian decksha...,13.0,Koda,0,0,https://twitter.com/dog_rates/status/890006608...,NaN,https://pbs.twimg.com/media/DFnwSY4WAAAMliS.jpg,Samoyed
11,889880896479866881,2017-07-25 16:11:53,Twitter for iPhone,This is Bruno. He is a service shark. Only get...,13.0,Bruno,0,0,https://twitter.com/dog_rates/status/889880896...,NaN,https://pbs.twimg.com/media/DFl99B1WsAITKsg.jpg,French Bulldog
12,889665388333682689,2017-07-25 01:55:32,Twitter for iPhone,Here's a puppo that seems to be on the fence a...,13.0,None,0,0,https://twitter.com/dog_rates/status/889665388...,puppo,https://pbs.twimg.com/media/DFi579UWsAAatzw.jpg,Pembroke
13,889638837579907072,2017-07-25 00:10:02,Twitter for iPhone,This is Ted. He does his best. Sometimes that'...,12.0,Ted,0,0,https://twitter.com/dog_rates/status/889638837...,NaN,https://pbs.twimg.com/media/DFihzFfXsAYGDPR.jpg,French Bulldog
14,889531135344209921,2017-07-24 17:02:04,Twitter for iPhone,This is Stuart. He's sporting his favorite fan...,13.0,Stuart,0,0,https://twitter.com/dog_rates/status/889531135...,puppo,https://pbs.twimg.com/media/DFg_2PVW0AEHN3p.jpg,Golden Retriever
15,889278841981685760,2017-07-24 00:19:32,Twitter for iPhone,This is Oliver. You're witnessing one of his m...,13.0,Oliver,0,0,https://twitter.com/dog_rates/status/889278841...,NaN,https://pbs.twimg.com/ext_tw_video_thumb/88927...,Whippet
16,888917238123831296,2017-07-23 00:22:39,Twitter for iPhone,This is Jim. He found a fren. Taught him how t...,12.0,Jim,0,0,https://twitter.com/dog_rates/status/888917238...,NaN,https://pbs.twimg.com/media/DFYRgsOUQAARGhO.jpg,Golden Retriever
17,888804989199671297,2017-07-22 16:56:37,Twitter for iPhone,This is Zeke. He has a new stick. Very proud o...,13.0,Zeke,0,0,https://twitter.com/dog_rates/status/888804989...,NaN,https://pbs.twimg.com/media/DFWra-3VYAA2piG.jpg,Golden Retriever
18,888554962724278272,2017-07-22 00:23:06,Twitter for iPhone,This is Ralphus. He's powering up. Attempting ...,13.0,Ralphus,0,0,https://twitter.com/dog_rates/status/888554962...,NaN,https://pbs.twimg.com/media/DFTH_O-UQAACu20.jpg,Siberian Husky
19,888078434458587136,2017-07-20 16:49:33,Twitter for iPhone,This is Gerald. He was just told he didn't get...,12.0,Gerald,0,0,https://twitter.com/dog_rates/status/888078434...,NaN,https://pbs.twimg.com/media/DFMWn56WsAAkA7B.jpg,French Bulldog
20,887705289381826560,2017-07-19 16:06:48,Twitter for iPhone,This is Jeffrey. He has a monopoly on the pool...,13.0,Jeffrey,0,0,https://twitter.com/dog_rates/status/887705289...,NaN,https://pbs.twimg.com/media/DFHDQBbXgAEqY7t.jpg,Basset
21,887517139158093824,2017-07-19 03:39:09,Twitter for iPhone,I've yet to rate a Venezuelan Hover Wiener. Th...,14.0,such,0,0,https://twitter.com/dog_rates/status/887517139...,NaN,https://pbs.twimg.com/ext_tw_video_thumb/88751...,NaN
22,887473957103951883,2017-07-19 00:47:34,Twitter for iPhone,This is Canela. She attempted some fancy porch...,13.0,Canela,0,0,https://twitter.com/dog_rates/status/887473957...,NaN,https://pbs.twimg.com/media/DFDw2tyUQAAAFke.jpg,Pembroke
23,887343217045368832,2017-07-18 16:08:03,Twitter for iPhone,You may not have known you needed to see this ...,13.0,None,0,0,https://twitter.com/dog_rates/status/887343217...,NaN,https://pbs.twimg.com/ext_tw_video_thumb/88734...,Mexican Hairless
24,887101392804085760,2017-07-18 00:07:08,Twitter for iPhone,This... is a Jubilant Antarctic House Bear. We...,12.0,None,0,0,https://twitter.com/dog_rates/status/887101392...,NaN,https://pbs.twimg.com/media/DE-eAq6UwAA-jaE.jpg,Samoyed
25,886983233522544640,2017-07-17 16:17:36,Twitter for iPhone,This is Maya. She's very shy. Rarely leaves he...,13.0,Maya,0,0,https://twitter.com/dog_rates/status/886983233...,NaN,https://pbs.twimg.com/media/DE8yicJW0AAAvBJ.jpg,Chihuahua
26,886736880519319552,2017-07-16 23:58:41,Twitter for iPhone,This is Mingus. He's a wonderful father to his...,13.0,Mingus,0,0,https://twitter.com/dog_rates/status/886736880...,NaN,https://pbs.twimg.com/media/DE5Se8FXcAAJFx4.jpg,Kuvasz
27,886680336477933568,2017-07-16 20:14:00,Twitter for iPhone,This is Derek. He's late for a dog meeting. 13...,13.0,Derek,0,0,https://twitter.com/dog_rates/status/886680336...,NaN,https://pbs.twimg.com/media/DE4fEDzWAAAyHMM.jpg,NaN
28,886366144734445568,2017-07-15 23:25:31,Twitter for iPhone,This is Roscoe. Another pupper fallen victim t...,12.0,Roscoe,0,0,https://twitter.com/dog_rates/status/886366144...,pupper,https://pbs.twimg.com/media/DE0BTnQUwAApKEH.jpg,French Bulldog
29,886267009285017600,2017-07-15 16:51:35,Twitter for iPhone,@NonWhiteHat @MayhewMayhem omg hello tanner yo...,12.0,None,0,1,https://twitter.com/dog_rates/status/886267009...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2094,666435652385423360,2015-11-17 02:00:15,Twitter for iPhone,"""Can you behave? You're ruining my wedding day...",10.0,None,0,0,https://twitter.com/dog_rates/status/666435652...,NaN,https://pbs.twimg.com/media/CT-nsTQWEAEkyDn.jpg,Chesapeake Bay Retriever
2095,666430724426358785,2015-11-17 01:40:41,Twitter for iPhone,Oh boy what a pup! Sunglasses take this one to...,6.0,None,0,0,https://twitter.com/dog_rates/status/666430724...,NaN,https://pbs.twimg.com/media/CT-jNYqW4AAPi2M.jpg,Irish Terrier
2096,666428276349472768,2015-11-17 01:30:57,Twitter for iPhone,Here we have an Austrian Pulitzer. Collectors ...,7.0,None,0,0,https://twitter.com/dog_rates/status/666428276...,NaN,https://pbs.twimg.com/media/CT-g-0DUwAEQdSn.jpg,Pembroke
2097,666421158376562688,2015-11-17 01:02:40,Twitter for iPhone,*internally screaming* 12/10,12.0,None,0,0,https://twitter.com/dog_rates/status/666421158...,NaN,https://pbs.twimg.com/media/CT-aggCXAAIMfT3.jpg,Blenheim Spaniel
2098,666418789513326592,2015-11-17 00:53:15,Twitter for iPhone,This is Walter. He is an Alaskan Terrapin. Lov...,10.0,Walter,0,0,https://twitter.com/dog_rates/status/666418789...,NaN,https://pbs.twimg.com/media/CT-YWb7U8AA7QnN.jpg,Toy Terrier
2099,666407126856765440,2015-11-17 00:06:54,Twitter for iPhone,This is a southern Vesuvius bumblegruff. Can d...,7.0,a,0,0,https://twitter.com/dog_rates/status/666407126...,NaN,https://pbs.twimg.com/media/CT-NvwmW4AAugGZ.jpg,Black-And-Tan Coonhound
2100,666396247373291520,2015-11-16 23:23:41,Twitter for iPhone,Oh goodness. A super rare northeast Qdoba kang...,9.0,None,0,0,https://twitter.com/dog_rates/status/666396247...,NaN,https://pbs.twimg.com/media/CT-D2ZHWIAA3gK1.jpg,Chihuahua
2101,666373753744588802,2015-11-16 21:54:18,Twitter for iPhone,Those are sunglasses and a jean jacket. 11/10 ...,11.0,None,0,0,https://twitter.com/dog_rates/status/666373753...,NaN,https://pbs.twimg.com/media/CT9vZEYWUAAlZ05.jpg,Soft-Coated Wheaten Terrier
2102,666362758909284353,2015-11-16 21:10:36,Twitter for iPhone,Unique dog here. Very small. Lives in containe...,6.0,None,0,0,https://twitter.com/dog_rates/status/666362758...,NaN,https://pbs.twimg.com/media/CT9lXGsUcAAyUFt.jpg,NaN
2103,666353288456101888,2015-11-16 20:32:58,Twitter for iPhone,Here we have a mixed Asiago from the Galápagos...,8.0,None,0,0,https://twitter.com/dog_rates/status/666353288...,NaN,https://pbs.twimg.com/media/CT9cx0tUEAAhNN_.jpg,Malamute
2104,666345417576210432,2015-11-16 20:01:42,Twitter for iPhone,Look at this jokester thinking seat belt laws ...,10.0,None,0,0,https://twitter.com/dog_rates/status/666345417...,NaN,https://pbs.twimg.com/media/CT9Vn7PWoAA_ZCM.jpg,Golden Retriever
2105,666337882303524864,2015-11-16 19:31:45,Twitter for iPhone,This is an extremely rare horned Parthenon. No...,9.0,an,0,0,https://twitter.com/dog_rates/status/666337882...,NaN,https://pbs.twimg.com/media/CT9OwFIWEAMuRje.jpg,Newfoundland
2106,666273097616637952,2015-11-16 15:14:19,Twitter for iPhone,Can take selfies 11/10,11.0,None,0,0,https://twitter.com/dog_rates/status/666273097...,NaN,https://pbs.twimg.com/media/CT8T1mtUwAA3aqm.jpg,Italian Greyhound
2107,666268910803644416,2015-11-16 14:57:41,Twitter for iPhone,Very concerned about fellow dog trapped in com...,10.0,None,0,0,https://twitter.com/dog_rates/status/666268910...,NaN,https://pbs.twimg.com/media/CT8QCd1WEAADXws.jpg,NaN
2108,666102155909144576,2015-11-16 03:55:04,Twitter for iPhone,Oh my. Here you are seeing an Adobe Setter giv...,11.0,None,0,0,https://twitter.com/dog_rates/status/666102155...,NaN,https://pbs.twimg.com/media/CT54YGiWUAEZnoK.jpg,English Setter
2109,666099513787052032,2015-11-16 03:44:34,Twitter for iPhone,Can stand on stump for what seems like a while...,8.0,None,0,0,https://twitter.com/dog_rates/status/666099513...,NaN,https://pbs.twimg.com/media/CT51-JJUEAA6hV8.jpg,Lhasa
2110,666094000022159362,2015-11-16 03:22:39,Twitter for iPhone,This appears to be a Mongolian Presbyterian mi...,9.0,None,0,0,https://twitter.com/dog_rates/status/666094000...,NaN,https://pbs.twimg.com/media/CT5w9gUW4AAsBNN.jpg,Bloodhound
2111,666082916733198337,2015-11-16 02:38:37,Twitter for iPhone,Here we have a well-established sunblockerspan...,6.0,None,0,0,https://twitter.com/dog_rates/status/666082916...,NaN,https://pbs.twimg.com/media/CT5m4VGWEAAtKc8.jpg,Pug
2112,666073100786774016,2015-11-16 01:59:36,Twitter for iPhone,Let's hope this flight isn't Malaysian (lol). ...,10.0,None,0,0,https://twitter.com/dog_rates/status/666073100...,NaN,https://pbs.twimg.com/media/CT5d9DZXAAALcwe.jpg,Walker Hound
2113,666071193221509120,2015-11-16 01:52:02,Twitter for iPhone,Here we have a northern speckled Rhododendron....,9.0,None,0,0,https://twitter.com/dog_rates/status/666071193...,NaN,https://pbs.twimg.com/media/CT5cN_3WEAAlOoZ.jpg,Gordon Setter
2114,666063827256086533,2015-11-16 01:22:45,Twitter for iPhone,This is the happiest dog you will ever see. Ve...,10.0,the,0,0,https://twitter.com/dog_rates/status/666063827...,NaN,https://pbs.twimg.com/media/CT5Vg_wXIAAXfnj.jpg,Golden Retriever
2115,666058600524156928,2015-11-16 01:01:59,Twitter for iPhone,Here is the Rand Paul of retrievers folks! He'...,8.0,the,0,0,https://twitter.com/dog_rates/status/666058600...,NaN,https://pbs.twimg.com/media/CT5Qw94XAAA_2dP.jpg,Miniature Poodle
2116,666057090499244032,2015-11-16 00:55:59,Twitter for iPhone,My oh my. This is a rare blond Canadian terrie...,9.0,a,0,0,https://twitter.com/dog_rates/status/666057090...,NaN,https://pbs.twimg.com/media/CT5PY90WoAAQGLo.jpg,Golden Retriever
2117,666055525042405380,2015-11-16 00:49:46,Twitter for iPhone,Here is a Siberian heavily armored polar bear ...,10.0,a,0,0,https://twitter.com/dog_rates/status/666055525...,NaN,https://pbs.twimg.com/media/CT5N9tpXIAAifs1.jpg,Chow
2118,666050758794694657,2015-11-16 00:30:50,Twitter for iPhone,This is a truly beautiful English Wilson Staff...,10.0,a,0,0,https://twitter.com/dog_rates/status/666050758...,NaN,https://pbs.twimg.com/media/CT5Jof1WUAEuVxN.jpg,Bernese Mountain Dog
2119,666049248165822465,2015-11-16 00:24:50,Twitter for iPhone,Here we have a 1949 1st generation vulpix. Enj...,5.0,None,0,0,https://twitter.com/dog_rates/status/666049248...,NaN,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,Miniature Pinscher
2120,666044226329800704,2015-11-16 00:04:52,Twitter for iPhone,This is a purebred Piers Morgan. Loves to Netf...,6.0,a,0,0,https://twitter.com/dog_rates/status/666044226...,NaN,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,Rhodesian Ridgeback
2121,666033412701032449,2015-11-15 23:21:54,Twitter for iPhone,Here is a very happy pup. Big fan of well-main...,9.0,a,0,0,https://twitter.com/dog_rates/status/666033412...,NaN,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,German Shepherd
2122,666029285002620928,2015-11-15 23:05:30,Twitter for iPhone,This is a western brown Mitsubishi terrier. Up...,7.0,a,0,0,https://twitter.com/dog_rates/status/666029285...,NaN,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,Redbone
2123,666020888022790149,2015-11-15 22:32:08,Twitter for iPhone,Here we have a Japanese Irish Setter. Lost eye...,8.0,None,0,0,https://twitter.com/dog_rates/status/666020888...,NaN,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,Welsh Springer Spaniel

#### Code

In [90]:
df_3c.tweet_id = df_3c.tweet_id.astype(str)

In [91]:
df=df.merge(df_3c, how='left', on= "tweet_id")

#### Check

In [92]:
df.shape

(2124, 14)

In [93]:
df.head()

,tweet_id,timestamp,source,text,rating_numerator,name,floofer,is_reply,url,stage,jpg_url,breed_fin,favorite_count,retweet_count
0,892420643555336193,2017-08-01 16:23:56,Twitter for iPhone,This is Phineas. He's a mystical boy. Only eve...,13.0,Phineas,0,0,https://twitter.com/dog_rates/status/892420643...,NaN,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,NaN,38689,8558
1,892177421306343426,2017-08-01 00:17:27,Twitter for iPhone,This is Tilly. She's just checking pup on you....,13.0,Tilly,0,0,https://twitter.com/dog_rates/status/892177421...,NaN,https://pbs.twimg.com/media/DGGmoV4XsAAUL6n.jpg,Chihuahua,33164,6292
2,891815181378084864,2017-07-31 00:18:03,Twitter for iPhone,This is Archie. He is a rare Norwegian Pouncin...,12.0,Archie,0,0,https://twitter.com/dog_rates/status/891815181...,NaN,https://pbs.twimg.com/media/DGBdLU1WsAANxJ9.jpg,Chihuahua,24966,4174
3,891689557279858688,2017-07-30 15:58:51,Twitter for iPhone,This is Darla. She commenced a snooze mid meal...,13.0,Darla,0,0,https://twitter.com/dog_rates/status/891689557...,NaN,https://pbs.twimg.com/media/DF_q7IAWsAEuuN8.jpg,Labrador Retriever,42074,8689
4,891327558926688256,2017-07-29 16:00:24,Twitter for iPhone,This is Franklin. He would like you to stop ca...,12.0,Franklin,0,0,https://twitter.com/dog_rates/status/891327558...,NaN,https://pbs.twimg.com/media/DF6hr6BUMAAzZgT.jpg,Basset,40227,9451

#### Issue 4: rearrange columns

#### Define
rearrange columns by subsetting the whole dataframe using the order desired for columns

#### Code

In [94]:
df= df[['tweet_id', 'timestamp', 'source','url', 'jpg_url', 'is_reply', 'text', 'name', 'rating_numerator', 'breed_fin', 'stage', 'floofer', 'favorite_count', 'retweet_count' ]]

#### Check

In [95]:
df

,tweet_id,timestamp,source,url,jpg_url,is_reply,text,name,rating_numerator,breed_fin,stage,floofer,favorite_count,retweet_count
0,892420643555336193,2017-08-01 16:23:56,Twitter for iPhone,https://twitter.com/dog_rates/status/892420643...,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,0,This is Phineas. He's a mystical boy. Only eve...,Phineas,13.0,NaN,NaN,0,38689,8558
1,892177421306343426,2017-08-01 00:17:27,Twitter for iPhone,https://twitter.com/dog_rates/status/892177421...,https://pbs.twimg.com/media/DGGmoV4XsAAUL6n.jpg,0,This is Tilly. She's just checking pup on you....,Tilly,13.0,Chihuahua,NaN,0,33164,6292
2,891815181378084864,2017-07-31 00:18:03,Twitter for iPhone,https://twitter.com/dog_rates/status/891815181...,https://pbs.twimg.com/media/DGBdLU1WsAANxJ9.jpg,0,This is Archie. He is a rare Norwegian Pouncin...,Archie,12.0,Chihuahua,NaN,0,24966,4174
3,891689557279858688,2017-07-30 15:58:51,Twitter for iPhone,https://twitter.com/dog_rates/status/891689557...,https://pbs.twimg.com/media/DF_q7IAWsAEuuN8.jpg,0,This is Darla. She commenced a snooze mid meal...,Darla,13.0,Labrador Retriever,NaN,0,42074,8689
4,891327558926688256,2017-07-29 16:00:24,Twitter for iPhone,https://twitter.com/dog_rates/status/891327558...,https://pbs.twimg.com/media/DF6hr6BUMAAzZgT.jpg,0,This is Franklin. He would like you to stop ca...,Franklin,12.0,Basset,NaN,0,40227,9451
5,891087950875897856,2017-07-29 00:08:17,Twitter for iPhone,https://twitter.com/dog_rates/status/891087950...,https://pbs.twimg.com/media/DF3HwyEWsAABqE6.jpg,0,Here we have a majestic great white breaching ...,None,13.0,Chesapeake Bay Retriever,NaN,0,20168,3128
6,890971913173991426,2017-07-28 16:27:12,Twitter for iPhone,https://twitter.com/dog_rates/status/890971913...,https://pbs.twimg.com/media/DF1eOmZXUAALUcq.jpg,0,Meet Jax. He enjoys ice cream so much he gets ...,Jax,13.0,Appenzeller,NaN,0,11817,2082
7,890729181411237888,2017-07-28 00:22:40,Twitter for iPhone,https://twitter.com/dog_rates/status/890729181...,https://pbs.twimg.com/media/DFyBahAVwAAhUTd.jpg,0,When you watch your owner call another dog a g...,None,13.0,Pomeranian,NaN,0,65363,18984
8,890609185150312448,2017-07-27 16:25:51,Twitter for iPhone,https://twitter.com/dog_rates/status/890609185...,https://pbs.twimg.com/media/DFwUU__XcAEpyXI.jpg,0,This is Zoey. She doesn't want to be one of th...,Zoey,13.0,Irish Terrier,NaN,0,27723,4282
9,890240255349198849,2017-07-26 15:59:51,Twitter for iPhone,https://twitter.com/dog_rates/status/890240255...,https://pbs.twimg.com/media/DFrEyVuW0AAO3t9.jpg,0,This is Cassie. She is a college pup. Studying...,Cassie,14.0,Pembroke,doggo,0,31862,7449
10,890006608113172480,2017-07-26 00:31:25,Twitter for iPhone,https://twitter.com/dog_rates/status/890006608...,https://pbs.twimg.com/media/DFnwSY4WAAAMliS.jpg,0,This is Koda. He is a South Australian decksha...,Koda,13.0,Samoyed,NaN,0,30582,7365
11,889880896479866881,2017-07-25 16:11:53,Twitter for iPhone,https://twitter.com/dog_rates/status/889880896...,https://pbs.twimg.com/media/DFl99B1WsAITKsg.jpg,0,This is Bruno. He is a service shark. Only get...,Bruno,13.0,French Bulldog,NaN,0,27727,4990
12,889665388333682689,2017-07-25 01:55:32,Twitter for iPhone,https://twitter.com/dog_rates/status/889665388...,https://pbs.twimg.com/media/DFi579UWsAAatzw.jpg,0,Here's a puppo that seems to be on the fence a...,None,13.0,Pembroke,puppo,0,48016,10110
13,889638837579907072,2017-07-25 00:10:02,Twitter for iPhone,https://twitter.com/dog_rates/status/889638837...,https://pbs.twimg.com/media/DFihzFfXsAYGDPR.jpg,0,This is Ted. He does his best. Sometimes that'...,Ted,12.0,French Bulldog,NaN,0,27113,4566
14,889531135344209921,2017-07-24 17:02:04,Twitter for iPhone,https://twitter.com/dog_rates/status/889531135...,https://pbs.twimg.com/media/DFg_2PVW0AEHN3p.jpg,0,This is Stuart. He's sporting his favorite fan...,Stuart,13.0,Golden Retriever,puppo,0,15061,2243
15,889278841981685760,2017-07-24 00:19:32,Twitter for iPhone,https://twitter.com/dog_rates/status/889278841...,https://pbs.twimg.com/ext_tw_video_thumb/88927...,0,This is Oliver. You're witnessing one of his m...,Oliver,13.0,Whippet,NaN,0,25244,5449
16,888917238123831296,2017-07-23 00:22:39,Twitter for iPhone,https://twitter.com/dog_rates/status/888917238...,https://pbs.twimg.com/media/DFYRgsOUQAARGhO.jpg,0,This is Jim. He found a fren. Taught him how t...,Jim,12.0,Golden Retriever,NaN,0,29005,4517
17,888804989199671297,2017-07-22 16:56:37,Twitter for iPhone,https://twitter.com/dog_rates/status/888804989...,https://pbs.twimg.com/media/DFWra-3VYAA2piG.jpg,0,This is Zeke. He has a new stick. Very proud o...,Zeke,13.0,Golden Retriever,NaN,0,25531,4363
18,888554962724278272,2017-07-22 00:23:06,Twitter for iPhone,https://twitter.com/dog_rates/status/888554962...,https://pbs.twimg.com/media/DFTH_O-UQAACu20.jpg,0,This is Ralphus. He's powering up. Attempting ...,Ralphus,13.0,Siberian Husky,NaN,0,19857,3595
19,888078434458587136,2017-07-20 16:49:33,Twitter for iPhone,https://twitter.com/dog_rates/status/888078434...,https://pbs.twimg.com/media/DFMWn56WsAAkA7B.jpg,0,This is Gerald. He was just told he didn't get...,Gerald,12.0,French Bulldog,NaN,0,21701,3510
20,887705289381826560,2017-07-19 16:06:48,Twitter for iPhone,https://twitter.com/dog_rates/status/887705289...,https://pbs.twimg.com/media/DFHDQBbXgAEqY7t.jpg,0,This is Jeffrey. He has a monopoly on the pool...,Jeffrey,13.0,Basset,NaN,0,30107,5415
21,887517139158093824,2017-07-19 03:39:09,Twitter for iPhone,https://twitter.com/dog_rates/status/887517139...,https://pbs.twimg.com/ext_tw_video_thumb/88751...,0,I've yet to rate a Venezuelan Hover Wiener. Th...,such,14.0,NaN,NaN,0,46125,11718
22,887473957103951883,2017-07-19 00:47:34,Twitter for iPhone,https://twitter.com/dog_rates/status/887473957...,https://pbs.twimg.com/media/DFDw2tyUQAAAFke.jpg,0,This is Canela. She attempted some fancy porch...,Canela,13.0,Pembroke,NaN,0,68943,18309
23,887343217045368832,2017-07-18 16:08:03,Twitter for iPhone,https://twitter.com/dog_rates/status/887343217...,https://pbs.twimg.com/ext_tw_video_thumb/88734...,0,You may not have known you needed to see this ...,None,13.0,Mexican Hairless,NaN,0,33595,10448
24,887101392804085760,2017-07-18 00:07:08,Twitter for iPhone,https://twitter.com/dog_rates/status/887101392...,https://pbs.twimg.com/media/DE-eAq6UwAA-jaE.jpg,0,This... is a Jubilant Antarctic House Bear. We...,None,12.0,Samoyed,NaN,0,30457,5988
25,886983233522544640,2017-07-17 16:17:36,Twitter for iPhone,https://twitter.com/dog_rates/status/886983233...,https://pbs.twimg.com/media/DE8yicJW0AAAvBJ.jpg,0,This is Maya. She's very shy. Rarely leaves he...,Maya,13.0,Chihuahua,NaN,0,35069,7808
26,886736880519319552,2017-07-16 23:58:41,Twitter for iPhone,https://twitter.com/dog_rates/status/886736880...,https://pbs.twimg.com/media/DE5Se8FXcAAJFx4.jpg,0,This is Mingus. He's a wonderful father to his...,Mingus,13.0,Kuvasz,NaN,0,12040,3312
27,886680336477933568,2017-07-16 20:14:00,Twitter for iPhone,https://twitter.com/dog_rates/status/886680336...,https://pbs.twimg.com/media/DE4fEDzWAAAyHMM.jpg,0,This is Derek. He's late for a dog meeting. 13...,Derek,13.0,NaN,NaN,0,22364,4488
28,886366144734445568,2017-07-15 23:25:31,Twitter for iPhone,https://twitter.com/dog_rates/status/886366144...,https://pbs.twimg.com/media/DE0BTnQUwAApKEH.jpg,0,This is Roscoe. Another pupper fallen victim t...,Roscoe,12.0,French Bulldog,pupper,0,21145,3209
29,886267009285017600,2017-07-15 16:51:35,Twitter for iPhone,https://twitter.com/dog_rates/status/886267009...,NaN,1,@NonWhiteHat @MayhewMayhem omg hello tanner yo...,None,12.0,NaN,NaN,0,116,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2094,666435652385423360,2015-11-17 02:00:15,Twitter for iPhone,https://twitter.com/dog_rates/status/666435652...,https://pbs.twimg.com/media/CT-nsTQWEAEkyDn.jpg,0,"""Can you behave? You're ruining my wedding day...",None,10.0,Chesapeake Bay Retriever,NaN,0,167,54
2095,666430724426358785,2015-11-17 01:40:41,Twitter for iPhone,https://twitter.com/dog_rates/status/666430724...,https://pbs.twimg.com/media/CT-jNYqW4AAPi2M.jpg,0,Oh boy what a pup! Sunglasses take this one to...,None,6.0,Irish Terrier,NaN,0,321,199
2096,666428276349472768,2015-11-17 01:30:57,Twitter for iPhone,https://twitter.com/dog_rates/status/666428276...,https://pbs.twimg.com/media/CT-g-0DUwAEQdSn.jpg,0,Here we have an Austrian Pulitzer. Collectors ...,None,7.0,Pembroke,NaN,0,166,84
2097,666421158376562688,2015-11-17 01:02:40,Twitter for iPhone,https://twitter.com/dog_rates/status/666421158...,https://pbs.twimg.com/media/CT-aggCXAAIMfT3.jpg,0,*internally screaming* 12/10,None,12.0,Blenheim Spaniel,NaN,0,318,111
2098,666418789513326592,2015-11-17 00:53:15,Twitter for iPhone,https://twitter.com/dog_rates/status/666418789...,https://pbs.twimg.com/media/CT-YWb7U8AA7QnN.jpg,0,This is Walter. He is an Alaskan Terrapin. Lov...,Walter,10.0,Toy Terrier,NaN,0,127,47
2099,666407126856765440,2015-11-17 00:06:54,Twitter for iPhone,https://twitter.com/dog_rates/status/666407126...,https://pbs.twimg.com/media/CT-NvwmW4AAugGZ.jpg,0,This is a southern Vesuvius bumblegruff. Can d...,a,7.0,Black-And-Tan Coonhound,NaN,0,110,41
2100,666396247373291520,2015-11-16 23:23:41,Twitter for iPhone,https://twitter.com/dog_rates/status/666396247...,https://pbs.twimg.com/media/CT-D2ZHWIAA3gK1.jpg,0,Oh goodness. A super rare northeast Qdoba kang...,None,9.0,Chihuahua,NaN,0,166,86
2101,666373753744588802,2015-11-16 21:54:18,Twitter for iPhone,https://twitter.com/dog_rates/status/666373753...,https://pbs.twimg.com/media/CT9vZEYWUAAlZ05.jpg,0,Those are sunglasses and a jean jacket. 11/10 ...,None,11.0,Soft-Coated Wheaten Terrier,NaN,0,189,93
2102,666362758909284353,2015-11-16 21:10:36,Twitter for iPhone,https://twitter.com/dog_rates/status/666362758...,https://pbs.twimg.com/media/CT9lXGsUcAAyUFt.jpg,0,Unique dog here. Very small. Lives in containe...,None,6.0,NaN,NaN,0,779,574
2103,666353288456101888,2015-11-16 20:32:58,Twitter for iPhone,https://twitter.com/dog_rates/status/666353288...,https://pbs.twimg.com/media/CT9cx0tUEAAhNN_.jpg,0,Here we have a mixed Asiago from the Galápagos...,None,8.0,Malamute,NaN,0,221,73
2104,666345417576210432,2015-11-16 20:01:42,Twitter for iPhone,https://twitter.com/dog_rates/status/666345417...,https://pbs.twimg.com/media/CT9Vn7PWoAA_ZCM.jpg,0,Look at this jokester thinking seat belt laws ...,None,10.0,Golden Retriever,NaN,0,299,139
2105,666337882303524864,2015-11-16 19:31:45,Twitter for iPhone,https://twitter.com/dog_rates/status/666337882...,https://pbs.twimg.com/media/CT9OwFIWEAMuRje.jpg,0,This is an extremely rare horned Parthenon. No...,an,9.0,Newfoundland,NaN,0,199,92
2106,666273097616637952,2015-11-16 15:14:19,Twitter for iPhone,https://twitter.com/dog_rates/status/666273097...,https://pbs.twimg.com/media/CT8T1mtUwAA3aqm.jpg,0,Can take selfies 11/10,None,11.0,Italian Greyhound,NaN,0,175,76
2107,666268910803644416,2015-11-16 14:57:41,Twitter for iPhone,https://twitter.com/dog_rates/status/666268910...,https://pbs.twimg.com/media/CT8QCd1WEAADXws.jpg,0,Very concerned about fellow dog trapped in com...,None,10.0,NaN,NaN,0,104,35
2108,666102155909144576,2015-11-16 03:55:04,Twitter for iPhone,https://twitter.com/dog_rates/status/666102155...,https://pbs.twimg.com/media/CT54YGiWUAEZnoK.jpg,0,Oh my. Here you are seeing an Adobe Setter giv...,None,11.0,English Setter,NaN,0,80,13
2109,666099513787052032,2015-11-16 03:44:34,Twitter for iPhone,https://twitter.com/dog_rates/status/666099513...,https://pbs.twimg.com/media/CT51-JJUEAA6hV8.jpg,0,Can stand on stump for what seems like a while...,None,8.0,Lhasa,NaN,0,156,68
2110,666094000022159362,2015-11-16 03:22:39,Twitter for iPhone,https://twitter.com/dog_rates/status/666094000...,https://pbs.twimg.com/media/CT5w9gUW4AAsBNN.jpg,0,This appears to be a Mongolian Presbyterian mi...,None,9.0,Bloodhound,NaN,0,164,74
2111,666082916733198337,2015-11-16 02:38:37,Twitter for iPhone,https://twitter.com/dog_rates/status/666082916...,https://pbs.twimg.com/media/CT5m4VGWEAAtKc8.jpg,0,Here we have a well-established sunblockerspan...,None,6.0,Pug,NaN,0,119,45
2112,666073100786774016,2015-11-16 01:59:36,Twitter for iPhone,https://twitter.com/dog_rates/status/666073100...,https://pbs.twimg.com/media/CT5d9DZXAAALcwe.jpg,0,Let's hope this flight isn't Malaysian (lol). ...,None,10.0,Walker Hound,NaN,0,322,164
2113,666071193221509120,2015-11-16 01:52:02,Twitter for iPhone,https://twitter.com/dog_rates/status/666071193...,https://pbs.twimg.com/media/CT5cN_3WEAAlOoZ.jpg,0,Here we have a northern speckled Rhododendron....,None,9.0,Gordon Setter,NaN,0,148,62
2114,666063827256086533,2015-11-16 01:22:45,Twitter for iPhone,https://twitter.com/dog_rates/status/666063827...,https://pbs.twimg.com/media/CT5Vg_wXIAAXfnj.jpg,0,This is the happiest dog you will ever see. Ve...,the,10.0,Golden Retriever,NaN,0,476,220
2115,666058600524156928,2015-11-16 01:01:59,Twitter for iPhone,https://twitter.com/dog_rates/status/666058600...,https://pbs.twimg.com/media/CT5Qw94XAAA_2dP.jpg,0,Here is the Rand Paul of retrievers folks! He'...,the,8.0,Miniature Poodle,NaN,0,112,57
2116,666057090499244032,2015-11-16 00:55:59,Twitter for iPhone,https://twitter.com/dog_rates/status/666057090...,https://pbs.twimg.com/media/CT5PY90WoAAQGLo.jpg,0,My oh my. This is a rare blond Canadian terrie...,a,9.0,Golden Retriever,NaN,0,298,142
2117,666055525042405380,2015-11-16 00:49:46,Twitter for iPhone,https://twitter.com/dog_rates/status/666055525...,https://pbs.twimg.com/media/CT5N9tpXIAAifs1.jpg,0,Here is a Siberian heavily armored polar bear ...,a,10.0,Chow,NaN,0,434,252
2118,666050758794694657,2015-11-16 00:30:50,Twitter for iPhone,https://twitter.com/dog_rates/status/666050758...,https://pbs.twimg.com/media/CT5Jof1WUAEuVxN.jpg,0,This is a truly beautiful English Wilson Staff...,a,10.0,Bernese Mountain Dog,NaN,0,132,58
2119,666049248165822465,2015-11-16 00:24:50,Twitter for iPhone,https://twitter.com/dog_rates/status/666049248...,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,0,Here we have a 1949 1st generation vulpix. Enj...,None,5.0,Miniature Pinscher,NaN,0,109,41
2120,666044226329800704,2015-11-16 00:04:52,Twitter for iPhone,https://twitter.com/dog_rates/status/666044226...,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,0,This is a purebred Piers Morgan. Loves to Netf...,a,6.0,Rhodesian Ridgeback,NaN,0,299,141
2121,666033412701032449,2015-11-15 23:21:54,Twitter for iPhone,https://twitter.com/dog_rates/status/666033412...,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,0,Here is a very happy pup. Big fan of well-main...,a,9.0,German Shepherd,NaN,0,125,45
2122,666029285002620928,2015-11-15 23:05:30,Twitter for iPhone,https://twitter.com/dog_rates/status/666029285...,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,0,This is a western brown Mitsubishi terrier. Up...,a,7.0,Redbone,NaN,0,129,47
2123,666020888022790149,2015-11-15 22:32:08,Twitter for iPhone,https://twitter.com/dog_rates/status/666020888...,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,0,Here we have a Japanese Irish Setter. Lost eye...,None,8.0,Welsh Springer Spaniel,NaN,0,2563,517

## Storing

We will be storing the following dataframes (names stored as mentioned after):

- df: twitter_archive_master.csv
- df_4: retweets_archive.csv
- df_5: replies_archive.csv

Amongst these twitter_archive_master.csv will be clean while retweets_archive.csv and replies_archive.csv will be in original format since they are not used for the analysis.

In [96]:
df.to_csv('twitter_archive_master.csv', index=False)
df_4.to_csv('retweets_archive.csv', index=False)
df_5.to_csv('replies_archive.csv', index=False)